"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowUpRight, Building2, ExternalLink, Plus, RefreshCw, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { dateKey } from "@/lib/workspace";
import { categoryLabel, emptyFinance, spendingByCurrency, type BankConnection, type FinanceView, type Transaction } from "@/lib/finance";

export const money=(value:number|null,currency:string|null)=>{if(value===null)return "Unavailable";if(!currency)return `${value.toFixed(2)} (currency unavailable)`;try{return new Intl.NumberFormat("en-US",{style:"currency",currency:currency||"USD"}).format(value);}catch{return `${value.toFixed(2)} ${currency||"(currency unknown)"}`;}};
type PlaidHandler={open:()=>void;destroy:()=>void};
type PlaidSDK={create:(options:{token:string;onSuccess:(token:string)=>void;onExit:(error:{display_message?:string}|null)=>void})=>PlaidHandler};
declare global {interface Window {Plaid?:PlaidSDK}}
let sdk:Promise<PlaidSDK>|undefined;
async function loadPlaid(){if(window.Plaid)return window.Plaid;if(!sdk)sdk=new Promise<PlaidSDK>((resolve,reject)=>{const script=document.createElement("script");script.src="https://cdn.plaid.com/link/v2/stable/link-initialize.js";script.onload=()=>window.Plaid?resolve(window.Plaid):reject(new Error("Plaid did not load."));script.onerror=()=>{script.remove();sdk=undefined;reject(new Error("Plaid could not load. Check your connection and try again."));};document.head.appendChild(script);});return sdk;}
export function FinancePanel(){
  const [view,setView]=useState<FinanceView>(emptyFinance);const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState("");
  const [setup,setSetup]=useState(false);const [accounts,setAccounts]=useState<BankConnection|null>(null);const [transaction,setTransaction]=useState<Transaction|null>(null);const [query,setQuery]=useState("");const [month,setMonth]=useState(()=>dateKey(new Date()).slice(0,7));
  const handler=useRef<PlaidHandler|null>(null);
  const load=useCallback(async()=>{const r=await fetch("/api/finance",{cache:"no-store"});const v=await r.json() as FinanceView&{error:string};if(!r.ok)throw new Error(v.error);setView(v);setLoaded(true);},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message));return()=>handler.current?.destroy();},[load]);
  const perform=useCallback(async(path:string,body:object={})=>{if(lock.current)throw new Error("Wait for the current request to finish.");lock.current=true;setBusy(true);setError("");try{const response=await fetch(`/api/finance${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const next=await response.json() as FinanceView&{error:string;linkToken:string};if(!response.ok){await load().catch(()=>{});throw new Error(next.error);}if(next.banks)setView(next);return next;}catch(e){setError(e instanceof Error?e.message:"The request failed.");throw e;}finally{lock.current=false;setBusy(false);}},[load]);
  useEffect(()=>{if(!view.banks.length)return;const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!lock.current)void perform("/sync").catch(()=>{});},3600000);return()=>clearInterval(timer);},[view.banks.length,perform]);
  async function connect(itemId?:string){try{setError("");const plaid=await loadPlaid();const {linkToken}=await perform("/link",itemId?{itemId}:{});handler.current?.destroy();handler.current=plaid.create({token:linkToken,onSuccess:token=>{void (itemId?perform("/sync"):perform("/exchange",{publicToken:token})).then((next:FinanceView)=>{if(!itemId){const bank=next.banks.find(b=>!b.accounts.some(a=>a.selected));if(bank)setAccounts(bank);}}).catch(()=>{});},onExit:err=>{if(err)setError(err.display_message||"Bank connection was not completed.");}});handler.current.open();}catch(e){setError(e instanceof Error?e.message:"Bank connection could not open.");}}
  const selected=view.banks.flatMap(b=>b.accounts.filter(a=>a.selected).map(a=>({...a,bank:b.name})));
  const totals=spendingByCurrency(view,month);const rows=view.transactions.filter(t=>t.date.startsWith(month)&&`${t.name} ${view.annotations[t.id]?.category||t.category} ${view.annotations[t.id]?.note||""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="life-panel"><div className="life-toolbar"><p>Capital One · Bank of America · Rivermark</p><div><Button variant="outline" disabled={busy} onClick={()=>setSetup(true)}>Connection setup</Button>{view.configured&&<Button disabled={busy} onClick={()=>void connect()}><Plus size={16}/> Connect a bank</Button>}{view.banks.length>0&&<Button variant="outline" disabled={busy} onClick={()=>void perform("/sync").catch(()=>{})}><RefreshCw size={15} className={busy?"spin":""}/> Sync</Button>}</div></div>
    {view.environment==="sandbox"&&<p className="life-banner">Sandbox mode · Sample bank data only</p>}
    {error&&<p className="form-error" role="alert">{error}</p>}
    {!loaded?<p>Loading finances…</p>:!view.banks.length?<section className="life-empty"><Wallet size={32}/><h2>Your finances, in one place.</h2><p>Connect your banks, then choose your personal accounts. See balances and transactions, and add your own categories and notes.</p><Button disabled={busy} onClick={()=>view.configured?void connect():setSetup(true)}>{view.configured?"Connect your first bank":"Set up bank connections"}<ArrowUpRight size={16}/></Button><p className="life-muted">Bank authentication happens through Plaid. Use Chrome or Safari for the bank’s sign-in window.</p></section>:<>
      <div className="life-metrics">{selected.map(a=><article className="life-metric" key={a.id}><span>{a.bank} · {a.mask?`••${a.mask}`:a.subtype}</span><strong>{money(a.current,a.currency)}</strong><p>{a.name}{a.type==="credit"?" · Amount owed":""}</p>{a.currency===null&&<small>Currency not supplied by bank</small>}</article>)}</div>
      <div className="bank-list">{view.banks.map(bank=><article className="bank-row" key={bank.id}><Building2 size={19}/><div><strong>{bank.name}</strong><p>{bank.lastSynced?`Last checked ${new Date(bank.lastSynced).toLocaleString()}`:"Choose accounts to begin"} · {bank.accounts.filter(a=>a.selected).length} selected</p>{bank.error&&<p className="form-error">{bank.error}</p>}{bank.updateStatus==="NOT_READY"&&<p>Transactions are still being prepared by the bank.</p>}</div><div className="bank-actions"><button className="text-button" disabled={busy} onClick={()=>setAccounts(bank)}>Choose accounts</button><button className="text-button" disabled={busy} onClick={()=>void connect(bank.id)}>Repair connection</button></div></article>)}</div>
      <section className="life-transactions"><div className="life-section-heading"><div><h2>Spending & transactions</h2><p>Posted purchases less refunds; transfers, loan payments, and pending items excluded.</p></div><label>Month<Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>
        <div className="spending-totals">{Object.entries(totals).map(([currency,amount])=><span key={currency}>{money(amount,currency)} <small>net spending</small></span>)}{!Object.keys(totals).length&&<span>No posted spending for this month</span>}</div>
        <label className="sr-only" htmlFor="transaction-search">Search transactions</label><Input id="transaction-search" placeholder="Search transactions, categories, or notes" value={query} onChange={e=>setQuery(e.target.value)}/>
        <div className="transaction-list">{rows.slice(0,300).map(t=><button className="transaction-row" key={t.id} disabled={busy} onClick={()=>setTransaction(t)}><span><strong>{t.name}</strong><small>{t.date} · {view.annotations[t.id]?.category||categoryLabel(t.category)}{t.pending?" · Pending":""}{view.annotations[t.id]?.excludeFromSpending?" · Excluded from spending":""}</small></span><span>{t.amount<0?"+":"−"}{money(Math.abs(t.amount),t.currency)}</span></button>)}{!rows.length&&<p className="life-muted">No matching transactions. Newly connected banks may take a few minutes to prepare history.</p>}{rows.length>300&&<p className="life-muted">Showing the first 300 matches. Narrow your search to see more.</p>}</div>
      </section><p className="life-muted">Balances are cached bank values. Transaction updates usually arrive a few times a day. Categories and notes you edit here stay in this workspace.</p>
    </>}
    <Dialog open={setup} onOpenChange={open=>!busy&&setSetup(open)}><DialogContent className="editor-dialog connection-dialog"><DialogTitle>Bank connection setup</DialogTitle><DialogDescription>Use your own Plaid developer access to connect your accounts.</DialogDescription><PlaidSetup configured={view.configured} blocked={view.banks.length>0} busy={busy} save={async body=>{await perform("/configure",body);setSetup(false);}}/>{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
    <Dialog open={!!accounts} onOpenChange={open=>!open&&!busy&&setAccounts(null)}><DialogContent className="editor-dialog connection-dialog">{accounts&&<AccountPicker bank={accounts} busy={busy} save={async ids=>{await perform("/accounts",{itemId:accounts.id,accountIds:ids});setAccounts(null);}} disconnect={async()=>{await perform("/disconnect",{itemId:accounts.id});setAccounts(null);}}/>}{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
    <Dialog open={!!transaction} onOpenChange={open=>!open&&!busy&&setTransaction(null)}><DialogContent className="editor-dialog">{transaction&&<TransactionEditor key={transaction.id} transaction={transaction} view={view} busy={busy} save={async body=>{await perform("/annotate",body);setTransaction(null);}}/>}{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
  </div>;
}
function PlaidSetup({configured,blocked,busy,save}:{configured:boolean;blocked:boolean;busy:boolean;save:(body:object)=>Promise<void>}){
  const [clientId,setClientId]=useState("");const [secret,setSecret]=useState("");const [environment,setEnvironment]=useState("production");
  return <form className="editor-form" onSubmit={e=>{e.preventDefault();void save({clientId,secret,environment}).catch(()=>{});}}><p className="connection-detail">Create a <a href="https://dashboard.plaid.com/signup" target="_blank" rel="noreferrer">Plaid developer account <ExternalLink size={12}/></a>, enable Transactions, and request eligible Production Trial access for real accounts. Trial access has a lifetime limit of 10 bank connections. Verify the plan shown in your Plaid dashboard before linking.</p><p className="connection-detail">Copy your client ID and matching environment secret from Plaid’s API Keys page. Credentials stay on this Mac.</p>{configured&&<p className="connection-detail">Plaid is configured.{blocked?" Disconnect existing banks before changing credentials.":" You can replace your credentials below."}</p>}<fieldset disabled={busy||blocked}><label htmlFor="plaid-client">Plaid client ID</label><Input id="plaid-client" required minLength={10} value={clientId} onChange={e=>setClientId(e.target.value)}/><label htmlFor="plaid-secret">Plaid secret</label><Input id="plaid-secret" type="password" required minLength={10} autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)}/><label htmlFor="plaid-environment">Environment</label><select id="plaid-environment" value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="production">Production / Trial — real accounts</option><option value="sandbox">Sandbox — sample accounts</option></select><Button className="life-submit" type="submit">Save Plaid connection</Button></fieldset></form>;
}
function AccountPicker({bank,busy,save,disconnect}:{bank:BankConnection;busy:boolean;save:(ids:string[])=>Promise<void>;disconnect:()=>Promise<void>}){
  const [ids,setIds]=useState(bank.accounts.filter(a=>a.selected).map(a=>a.id));const [confirm,setConfirm]=useState(false);
  return <><DialogTitle>{bank.name}</DialogTitle><DialogDescription>Choose only the personal checking, savings, and credit card accounts you want in this workspace.</DialogDescription><div className="account-picker">{bank.accounts.map(a=><label key={a.id}><input type="checkbox" checked={ids.includes(a.id)} disabled={busy||a.blocked||!["depository","credit"].includes(a.type)} onChange={e=>setIds(e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/><span>{a.name} {a.mask&&`••${a.mask}`}<small>{a.blocked?"Work or business account excluded":a.subtype}</small></span></label>)}</div>{!bank.accounts.length&&<p>Account details are unavailable. Close this dialog and sync to try again.</p>}<Button disabled={busy} onClick={()=>void save(ids).catch(()=>{})}>Save selected accounts</Button><button className="text-button" disabled={busy} onClick={()=>setConfirm(!confirm)}>Disconnect this bank</button>{confirm&&<div className="delete-confirm"><p>Revoke this Plaid bank connection and remove its cached data and notes from this Mac?</p><Button variant="destructive" disabled={busy} onClick={()=>void disconnect().catch(()=>{})}>Disconnect bank</Button></div>}</>;
}
function TransactionEditor({transaction:t,view,busy,save}:{transaction:Transaction;view:FinanceView;busy:boolean;save:(body:object)=>Promise<void>}){
  const original=useRef(view.annotations[t.id]).current;const [category,setCategory]=useState(original?.category||"");const [note,setNote]=useState(original?.note||"");const [exclude,setExclude]=useState(original?.excludeFromSpending||false);
  return <><DialogTitle>{t.name}</DialogTitle><DialogDescription>{t.date} · {money(t.amount,t.currency)}{t.pending?" · Pending":""}</DialogDescription><form className="editor-form" onSubmit={e=>{e.preventDefault();void save({transactionId:t.id,category,note,excludeFromSpending:exclude,revision:original?.revision||0}).catch(()=>{});}}><label htmlFor="transaction-category">Your category</label><Input id="transaction-category" maxLength={80} disabled={busy} placeholder={categoryLabel(t.category)} value={category} onChange={e=>setCategory(e.target.value)}/><label htmlFor="transaction-note">Notes</label><textarea id="transaction-note" maxLength={2000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/><label className="all-day-control"><input type="checkbox" disabled={busy} checked={exclude} onChange={e=>setExclude(e.target.checked)}/> Exclude from spending totals</label><p className="connection-detail">These edits are saved in your workspace. The bank’s transaction remains unchanged.</p><Button className="life-submit" type="submit" disabled={busy}>Save transaction notes</Button></form></>;
}
