"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, Download, Heart, Moon, Plus, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { emptyHealth, type HealthView } from "@/lib/health";
import { dateKey } from "@/lib/workspace";

const value=(amount:number|null|undefined,suffix="")=>amount==null?"No accessible data":`${Math.round(amount).toLocaleString()}${suffix}`;
export function HealthPanel(){
  const [view,setView]=useState<HealthView>(emptyHealth);const [busy,setBusy]=useState(false);const locked=useRef(false);const [error,setError]=useState("");const [setup,setSetup]=useState(false);const [weight,setWeight]=useState(false);const [day,setDay]=useState(()=>dateKey(new Date()));
  const load=useCallback(async()=>{const response=await fetch("/api/health",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setView(data);},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message));const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!locked.current)void load().catch(e=>setError(e.message));},10000);return()=>clearInterval(timer);},[load]);
  async function perform(path:string,body:object={}){if(locked.current)throw new Error("Wait for the current request to finish.");locked.current=true;setBusy(true);setError("");try{const response=await fetch(`/api/health${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);if("snapshot" in data)setView(data);return data;}catch(e){setError(e instanceof Error?e.message:"The request failed.");throw e;}finally{locked.current=false;setBusy(false);}}
  async function pairing(){try{const data=await perform("/pairing");const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="workspace-health-pairing.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch{}}
  const current=view.snapshot?.days.find(d=>d.date===day);const recent=view.snapshot?.days.filter(d=>d.date<=day).slice(-7)||[];
  const workouts=view.snapshot?.workouts.filter(w=>new Intl.DateTimeFormat("en-CA",{timeZone:view.snapshot!.timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(w.start))===day)||[];
  return <div className="life-panel"><div className="life-toolbar"><p>Apple Health · {view.lastSynced?`Last synced ${new Date(view.lastSynced).toLocaleString()}`:"Waiting for your iPhone"}</p><div><Button variant="outline" onClick={()=>setSetup(true)}>iPhone setup</Button><Button disabled={busy||!view.paired} onClick={()=>setWeight(true)}><Plus size={16}/> Log weight</Button></div></div>
    {(error||view.error)&&<p className="form-error" role="alert">{error||view.error}</p>}
    {!view.snapshot?<section className="life-empty"><Heart size={32}/><h2>A place for your health, too.</h2><p>See steps, sleep, workouts, resting heart rate, and weight from your iPhone. Review weight entries on your phone before they’re saved to Apple Health.</p><Button onClick={()=>setSetup(true)}><Smartphone size={16}/> Connect your iPhone</Button><p className="life-muted">Your health snapshot travels directly between your iPhone and this Mac over an encrypted local connection.</p></section>:<>
      <div className="life-section-heading"><h2>Your health on this day</h2><label>Day<Input type="date" value={day} min={view.snapshot.from} max={view.snapshot.to} onChange={e=>setDay(e.target.value)}/></label></div>
      <div className="life-metrics"><article className="life-metric"><span><Activity size={16}/> Steps</span><strong>{value(current?.steps)}</strong><p>Within this calendar day</p></article><article className="life-metric"><span><Moon size={16}/> Sleep</span><strong>{current?.sleepMinutes==null?"No accessible data":`${Math.floor(current.sleepMinutes/60)}h ${Math.round(current.sleepMinutes%60)}m`}</strong><p>Asleep time within this day</p></article><article className="life-metric"><span><Heart size={16}/> Resting heart rate</span><strong>{value(current?.restingHeartRate," bpm")}</strong><p>Latest measurement that day</p></article><article className="life-metric"><span>Weight</span><strong>{current?.weightKg==null?"No accessible data":`${(current.weightKg*2.2046226218).toFixed(1)} lb`}</strong><p>{current?.weightKg!=null?`${current.weightKg.toFixed(1)} kg`:"Latest measurement that day"}</p></article></div>
      <section className="life-transactions"><div className="life-section-heading"><h2>Your recent movement</h2><span className="life-muted">{view.snapshot.timeZone}</span></div><div className="health-bars">{recent.map(d=><div key={d.date}><span>{d.steps==null?"—":Math.round(d.steps).toLocaleString()}</span><div className="health-bar-track"><div style={{height:d.steps==null?0:`${Math.max(2,d.steps/Math.max(1,...recent.map(x=>x.steps||0))*100)}%`}}/></div><small>{d.date.slice(5)}</small></div>)}</div><p className="life-muted">Steps by day. A dash means no accessible data.</p></section>
      <section className="life-transactions"><div className="life-section-heading"><h2>Workouts</h2></div>{workouts.map(w=><div className="transaction-row" key={w.id}><span><strong>{w.name}</strong><small>{new Date(w.start).toLocaleTimeString([], {hour:"numeric",minute:"2-digit",timeZone:view.snapshot!.timeZone})}</small></span><span>{Math.round(w.minutes)} min</span></div>)}{!workouts.length&&<p className="life-muted">No accessible workouts for this day.</p>}</section>
    </>}
    {view.commands.length>0&&<section className="life-transactions"><div className="life-section-heading"><h2>Health entries</h2><p>Pending entries need your confirmation in the iPhone companion.</p></div>{view.commands.slice(-20).reverse().map(c=><div className="transaction-row" key={c.id}><span><strong>Weight · {c.kg.toFixed(2)} kg</strong><small>{new Date(c.measuredAt).toLocaleString()}</small></span><span className={`health-entry-status ${c.status}`}>{c.status==="applied"?"Saved in Apple Health":"Awaiting iPhone confirmation"}</span></div>)}</section>}
    <Dialog open={setup} onOpenChange={open=>!busy&&setSetup(open)}><DialogContent className="editor-dialog connection-dialog"><DialogTitle>Connect Apple Health</DialogTitle><DialogDescription>Pair the Workspace Health companion on your iPhone with this Mac.</DialogDescription><ol className="setup-steps"><li><strong>Install the companion.</strong> Open its Xcode project, select your personal signing team and connected iPhone, then run it. <Button variant="outline" disabled={busy} onClick={()=>void perform("/open-companion").catch(()=>{})}>Open companion in Xcode</Button></li><li><strong>Enable the local connection.</strong> Keep both devices on the same Wi-Fi. The workspace itself stays local to this Mac; only the paired health connection listens on Wi-Fi.</li><li><strong>Pair your phone.</strong> Download the pairing file, AirDrop it to your iPhone, and choose “Import pairing file” in the companion. The file expires after 10 minutes and works once. Allow Health and Local Network access on the phone.</li></ol>
      {!view.enabled?<HealthEnable addresses={view.addresses} busy={busy} enable={address=>perform("/enable",{address})}/>:<div className="health-connection-state"><p>{view.online?"Local health connection is running":"Local health connection needs attention"}{view.paired?" · iPhone paired":" · Awaiting pairing"}</p><Button disabled={busy||!view.online} onClick={()=>void pairing()}><Download size={16}/> Download pairing file</Button><button className="text-button" disabled={busy} onClick={()=>void perform("/disable").catch(()=>{})}>Disable iPhone sync and revoke pairing</button></div>}
      <p className="connection-detail">Open the companion and tap Sync now. Sync also runs when you reopen it. The Mac must be awake with the workspace running. Free Apple signing needs renewal after seven days.</p>{(error||view.error)&&<p className="form-error" role="alert">{error||view.error}</p>}</DialogContent></Dialog>
    <Dialog open={weight} onOpenChange={open=>!busy&&setWeight(open)}><DialogContent className="editor-dialog"><DialogTitle>Log a weight measurement</DialogTitle><DialogDescription>Send an actual measurement to your iPhone for review before saving it to Apple Health.</DialogDescription><WeightEditor busy={busy} save={async body=>{await perform("/weight",body);setWeight(false);}}/>{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
  </div>;
}
function HealthEnable({addresses,busy,enable}:{addresses:string[];busy:boolean;enable:(address:string)=>Promise<unknown>}){const [selected,setSelected]=useState(addresses[0]||"");return <div className="editor-form"><label htmlFor="health-address">This Mac’s Wi-Fi address</label><select id="health-address" value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{addresses.map(address=><option key={address}>{address}</option>)}</select>{!addresses.length&&<p className="form-error">Connect the Mac to Wi-Fi, then reopen these settings.</p>}<Button className="life-submit" disabled={busy||!addresses.includes(selected)} onClick={()=>void enable(selected).catch(()=>{})}>Enable iPhone sync</Button></div>;}
function WeightEditor({busy,save}:{busy:boolean;save:(body:object)=>Promise<void>}){const [amount,setAmount]=useState("");const [unit,setUnit]=useState("lb");const [time,setTime]=useState(()=>{const d=new Date();return `${dateKey(d)}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;});const requestId=useRef(crypto.randomUUID());return <form className="editor-form" onSubmit={e=>{e.preventDefault();const kg=Number(amount)/(unit==="lb"?2.2046226218:1);void save({id:requestId.current,kg:Math.round(kg*10000)/10000,measuredAt:new Date(time).toISOString()}).catch(()=>{});}}><div className="form-row"><div><label htmlFor="weight-value">Weight</label><Input id="weight-value" required type="number" min="1" max={unit==="lb"?1500:700} step="0.01" disabled={busy} value={amount} onChange={e=>{setAmount(e.target.value);requestId.current=crypto.randomUUID();}}/></div><div><label htmlFor="weight-unit">Unit</label><select id="weight-unit" disabled={busy} value={unit} onChange={e=>{setUnit(e.target.value);requestId.current=crypto.randomUUID();}}><option value="lb">Pounds</option><option value="kg">Kilograms</option></select></div></div><label htmlFor="weight-time">Measured at</label><Input id="weight-time" type="datetime-local" required disabled={busy} value={time} onChange={e=>{setTime(e.target.value);requestId.current=crypto.randomUUID();}}/><Button className="life-submit" disabled={busy} type="submit">Send to iPhone for confirmation</Button></form>;}

export function LifeOverview({day,open}:{day:string;open:(view:"finance"|"health")=>void}){
  const [health,setHealth]=useState<HealthView|null>(null);const [banks,setBanks]=useState<number|null>(null);
  useEffect(()=>{let active=true;const load=async()=>{const results=await Promise.allSettled([fetch("/api/health").then(r=>r.ok?r.json():null),fetch("/api/finance").then(r=>r.ok?r.json():null)]);if(!active)return;if(results[0].status==="fulfilled")setHealth(results[0].value);if(results[1].status==="fulfilled")setBanks(results[1].value?.banks?.length??null);};void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},60000);return()=>{active=false;clearInterval(timer);};},[]);
  const snapshot=health?.snapshot?.days.find(d=>d.date===day);
  return <section className="life-overview"><h2>A wider view</h2><button onClick={()=>open("finance")}><span>Finances</span><strong>{banks?`${banks} bank${banks===1?"":"s"} connected`:"Connect your banks"}</strong></button><button onClick={()=>open("health")}><span>Apple Health</span><strong>{snapshot?value(snapshot.steps," steps"):health?.paired?"Waiting for a health snapshot":"Connect your iPhone"}</strong></button></section>;
}
