"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, Download, Heart, Moon, Plus, Smartphone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { emptyHealth, healthWorkoutDay, healthWorkoutTimeZone, uniqueHealthWorkouts, type HealthView } from "@/lib/health";
import { dateKey } from "@/lib/workspace";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { SleepPanel } from "@/components/sleep";
import { useIntegrations } from "@/components/integrations";
import { focusNames, sessionSends, type ClimbingState } from "@/lib/climbing";
import { eventOnDay, type IntegrationLink } from "@/lib/integrations/model";

const value=(amount:number|null|undefined,suffix="")=>amount==null?"No accessible data":`${Math.round(amount).toLocaleString()}${suffix}`;
export function HealthPanel({active=true,selectedDay}:{active?:boolean;selectedDay?:string}){
  const [view,setView]=useState<HealthView>(emptyHealth);const [busy,setBusy]=useState(false);const locked=useRef(false);const [error,setError]=useState("");const [weight,setWeight]=useState(false);const [day,setDay]=useState(()=>selectedDay??dateKey(new Date()));
  const load=useCallback(async()=>{const response=await fetch("/api/health",{cache:"no-store"});const data=await response.json() as HealthView&{error:string};if(!response.ok)throw new Error(data.error);setView(data);setError("");},[]);
  useEffect(()=>{if(!active)return;const initial=setTimeout(()=>void load().catch(e=>setError(e.message)),0);const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!locked.current)void load().catch(e=>setError(e.message));},10000);return()=>{clearTimeout(initial);clearInterval(timer);};},[active,load]);
  async function perform(path:string,body:object={}){if(locked.current)throw new Error("Wait for the current request to finish.");locked.current=true;setBusy(true);setError("");try{const response=await fetch(`/api/health${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json() as HealthView&{error:string};if(!response.ok)throw new Error(data.error);if("snapshot" in data)setView(data);return data;}catch(e){setError(e instanceof Error?e.message:"The request failed.");throw e;}finally{locked.current=false;setBusy(false);}}
  const current=view.snapshot?.days.find(d=>d.date===day);const recent=view.snapshot?.days.filter(d=>d.date<=day).slice(-7)||[];
  const workouts=view.snapshot?uniqueHealthWorkouts(view.snapshot.workouts).filter(w=>healthWorkoutDay(w,view.snapshot!.timeZone)===day):[];
  const hasCurrentMetrics=!!current&&[current.steps,current.sleepMinutes,current.restingHeartRate,current.weightKg].some(amount=>amount!=null);
  const hasRecentMovement=recent.some(item=>item.steps!=null);
  const openSettings=()=>window.dispatchEvent(new CustomEvent("workspace:open-settings"));
  return <div className="life-panel">
    {(error||view.error)&&<div className="settings-link-notice"><p className="form-error" role="alert">Health data needs attention.</p><Button variant="outline" onClick={openSettings}>Open Settings</Button></div>}
    <Tabs defaultValue="sleep" className="health-tabs"><TabsList aria-label="Health views"><TabsTrigger value="sleep"><Moon size={16}/>Sleep</TabsTrigger><TabsTrigger value="overview"><Activity size={16}/>Overview</TabsTrigger></TabsList><TabsContent value="sleep" forceMount><SleepPanel active={active} openSettings={openSettings}/></TabsContent><TabsContent value="overview">
    {!view.snapshot?<section className="life-empty"><Heart size={32}/><h2>A place for your health, too.</h2><p>See steps, sleep, workouts, resting heart rate, and weight from your iPhone. Review weight entries on your phone before they’re saved to Apple Health.</p><Button onClick={openSettings}><Smartphone size={16}/> Open Settings</Button></section>:<>
      <div className="life-section-heading"><h2>Your health on this day</h2><div className="health-overview-actions"><label>Day<Input type="date" value={day} min={view.snapshot.from} max={view.snapshot.to} onChange={e=>setDay(e.target.value)}/></label><Button disabled={busy||!view.paired} onClick={()=>setWeight(true)}><Plus size={16}/> Log weight</Button></div></div>
      {hasCurrentMetrics&&<div className="life-metrics">{current?.steps!=null&&<article className="life-metric"><span><Activity size={16}/> Steps</span><strong>{value(current.steps)}</strong></article>}{current?.sleepMinutes!=null&&<article className="life-metric"><span><Moon size={16}/> Sleep</span><strong>{Math.floor(current.sleepMinutes/60)}h {Math.round(current.sleepMinutes%60)}m</strong></article>}{current?.restingHeartRate!=null&&<article className="life-metric"><span><Heart size={16}/> Resting heart rate</span><strong>{value(current.restingHeartRate," bpm")}</strong></article>}{current?.weightKg!=null&&<article className="life-metric"><span>Weight</span><strong>{(current.weightKg*2.2046226218).toFixed(1)} lb</strong><p>{current.weightKg.toFixed(1)} kg</p></article>}</div>}
      {hasRecentMovement&&<section className="life-transactions"><div className="life-section-heading"><h2>Recent movement</h2><span className="life-muted">{view.snapshot.timeZone}</span></div><div className="health-bars">{recent.map(d=><div key={d.date}><span>{d.steps==null?"—":Math.round(d.steps).toLocaleString()}</span><div className="health-bar-track"><div style={{height:d.steps==null?0:`${Math.max(2,d.steps/Math.max(1,...recent.map(x=>x.steps||0))*100)}%`}}/></div><small>{d.date.slice(5)}</small></div>)}</div></section>}
      {workouts.length>0&&<section className="life-transactions"><div className="life-section-heading"><h2>Workouts</h2></div>{workouts.map(w=><div className="transaction-row" key={w.id.toLowerCase()}><span><strong>{w.name}</strong><small>{new Date(w.start).toLocaleTimeString([], {hour:"numeric",minute:"2-digit",timeZone:healthWorkoutTimeZone(w,view.snapshot!.timeZone)})}</small></span><span>{Math.round(w.minutes)} min</span></div>)}</section>}
    </>}
    </TabsContent></Tabs>
    {view.commands.length>0&&<section className="life-transactions"><div className="life-section-heading"><h2>Health entries</h2><p>Pending entries need your confirmation in the iPhone companion.</p></div>{view.commands.slice(-20).reverse().map(c=><div className="transaction-row" key={c.id}><span><strong>Weight · {c.kg.toFixed(2)} kg</strong><small>{new Date(c.measuredAt).toLocaleString()}</small></span><span className={`health-entry-status ${c.status}`}>{c.status==="applied"?"Saved in Apple Health":"Awaiting iPhone confirmation"}</span></div>)}</section>}
    <Dialog open={weight} onOpenChange={open=>!busy&&setWeight(open)}><DialogContent className="editor-dialog"><DialogTitle>Log a weight measurement</DialogTitle><DialogDescription>Send an actual measurement to your iPhone for review before saving it to Apple Health.</DialogDescription><WeightEditor busy={busy} save={async body=>{await perform("/weight",body);setWeight(false);}}/>{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
  </div>;
}
export function HealthConnectionSettings({active=true}:{active?:boolean}){
  const [view,setView]=useState<HealthView>(emptyHealth);const [busy,setBusy]=useState(false);const locked=useRef(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/health",{cache:"no-store"});const data=await response.json() as HealthView&{error:string};if(!response.ok)throw new Error(data.error);setView(data);setError("");},[]);
  useEffect(()=>{if(!active)return;const initial=setTimeout(()=>void load().catch(e=>setError(e instanceof Error?e.message:"Health settings could not be loaded.")),0);const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!locked.current)void load().catch(()=>{});},5000);return()=>{clearTimeout(initial);clearInterval(timer);};},[active,load]);
  async function perform(path:string,body:object={}){if(locked.current)throw new Error("Wait for the current request to finish.");locked.current=true;setBusy(true);setError("");try{const response=await fetch(`/api/health${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json() as HealthView&{error:string};if(!response.ok)throw new Error(data.error);if("snapshot" in data)setView(data);else await load();return data;}catch(e){setError(e instanceof Error?e.message:"The request failed.");throw e;}finally{locked.current=false;setBusy(false);}}
  async function pairing(){try{const data=await perform("/pairing");const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="workspace-pairing.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch{}}
  return <div className="settings-stack"><div className="settings-section-heading"><div><h2>iPhone and Apple Health</h2><p>Local pairing, Health access, and the direct connection to this Mac.</p></div>{view.enabled&&!view.online&&<Button variant="outline" disabled={busy} onClick={()=>void perform("/retry").catch(()=>{})}>Retry connection</Button>}</div>
    <div className="connection-card"><div className="connection-card-heading"><span className="service-symbol health-symbol"><Smartphone size={20}/></span><div><h3>Workspace for iPhone</h3><p>{view.lastSynced?`Health last received ${new Date(view.lastSynced).toLocaleString()}`:"No Health snapshot received yet"}</p></div><span className={`connection-state ${view.online&&view.paired?"connected":""}`}>{view.online?(view.paired?"Paired":"Ready to pair"):view.enabled?"Needs attention":"Not enabled"}</span></div>
      <ol className="setup-steps"><li><strong>Install the iPhone app.</strong> Open its Xcode project, select your personal signing team and connected iPhone, then run it. <Button variant="outline" disabled={busy} onClick={()=>void perform("/open-companion").catch(()=>{})}>Open app in Xcode</Button></li><li><strong>Enable the local connection.</strong> Keep both devices on the same private Wi-Fi. Only a certificate-pinned Workspace connection listens on Wi-Fi.</li><li><strong>Pair your phone.</strong> Download the pairing file, AirDrop it to your iPhone, then choose it from Settings in the iPhone app. The file expires after 10 minutes and works once.</li></ol>
      {!view.enabled?<HealthEnable addresses={view.addresses} busy={busy} enable={address=>perform("/enable",{address})}/>:<div className="health-connection-state"><p>{view.online?"Local Workspace connection is running":"Local Workspace connection needs attention"}{view.paired?view.phoneScope==="workspace"?" · Workspace companion paired":" · Health-only pairing; download a new companion pairing file":" · Awaiting pairing"}</p><Button disabled={busy||!view.online} onClick={()=>void pairing()}><Download size={16}/> Download Workspace pairing file</Button><button className="text-button" disabled={busy} onClick={()=>void perform("/disable").catch(()=>{})}>Disable iPhone sync and revoke pairing</button></div>}
      <p className="connection-detail">On iPhone, use Settings to review Health permissions, sync Apple Health, or import older sleep history. The Mac must be awake with Workspace running. Free Apple signing needs renewal after seven days.</p>
    </div>{(error||view.error)&&<p className="form-error" role="alert">{error||view.error}</p>}
  </div>;
}
function HealthEnable({addresses,busy,enable}:{addresses:string[];busy:boolean;enable:(address:string)=>Promise<unknown>}){const [selected,setSelected]=useState(addresses[0]||"");return <div className="editor-form"><label htmlFor="health-address">This Mac’s Wi-Fi address</label><select id="health-address" value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}>{addresses.map(address=><option key={address}>{address}</option>)}</select>{!addresses.length&&<p className="form-error">Connect the Mac to Wi-Fi, then reopen these settings.</p>}<Button className="life-submit" disabled={busy||!addresses.includes(selected)} onClick={()=>void enable(selected).catch(()=>{})}>Enable iPhone sync</Button></div>;}
function WeightEditor({busy,save}:{busy:boolean;save:(body:object)=>Promise<void>}){const [amount,setAmount]=useState("");const [unit,setUnit]=useState("lb");const [time,setTime]=useState(()=>{const d=new Date();return `${dateKey(d)}T${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;});const requestId=useRef(crypto.randomUUID());return <form className="editor-form" onSubmit={e=>{e.preventDefault();const kg=Number(amount)/(unit==="lb"?2.2046226218:1);void save({id:requestId.current,kg:Math.round(kg*10000)/10000,measuredAt:new Date(time).toISOString()}).catch(()=>{});}}><div className="form-row"><div><label htmlFor="weight-value">Weight</label><Input id="weight-value" required type="number" min="1" max={unit==="lb"?1500:700} step="0.01" disabled={busy} value={amount} onChange={e=>{setAmount(e.target.value);requestId.current=crypto.randomUUID();}}/></div><div><label htmlFor="weight-unit">Unit</label><select id="weight-unit" disabled={busy} value={unit} onChange={e=>{setUnit(e.target.value);requestId.current=crypto.randomUUID();}}><option value="lb">Pounds</option><option value="kg">Kilograms</option></select></div></div><label htmlFor="weight-time">Measured at</label><Input id="weight-time" type="datetime-local" required disabled={busy} value={time} onChange={e=>{setTime(e.target.value);requestId.current=crypto.randomUUID();}}/><Button className="life-submit" disabled={busy} type="submit">Send to iPhone for confirmation</Button></form>;}

export function LifeOverview({day,open}:{day:string;open:(view:"finance"|"health"|"climbing")=>void}){
  const {view:integrations}=useIntegrations();
  const [health,setHealth]=useState<HealthView|null>(null);const [climbing,setClimbing]=useState<ClimbingState|null>(null);const [climbingLoaded,setClimbingLoaded]=useState(false);
  useEffect(()=>{let active=true;const load=async()=>{const results=await Promise.allSettled([fetch("/api/health").then(r=>r.ok?r.json() as Promise<HealthView>:null),fetch("/api/climbing").then(r=>r.ok?r.json() as Promise<ClimbingState>:null)]);if(!active)return;if(results[0].status==="fulfilled")setHealth(results[0].value);if(results[1].status==="fulfilled")setClimbing(results[1].value);setClimbingLoaded(true);};void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},60000);return()=>{active=false;clearInterval(timer);};},[]);
  const snapshot=health?.snapshot?.days.find(d=>d.date===day);
  const daySessions=climbing?.sessions.filter(session=>!session.deletedAt&&session.date===day).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))??[];
  const activeGoals=climbing?.goals.filter(goal=>!goal.archivedAt&&goal.status==="active").sort((a,b)=>(a.targetDate??"9999-12-31").localeCompare(b.targetDate??"9999-12-31")||b.updatedAt.localeCompare(a.updatedAt))??[];
  const scheduledLink=(planId:string):IntegrationLink|undefined=>integrations.links.find(link=>link.entityKind==="plan"&&link.entityId===planId&&link.role==="scheduled-session"&&link.provider==="google");
  const dayPlans=(climbing?.plans??[]).filter(plan=>plan.status==="planned").map(plan=>{const link=scheduledLink(plan.id);const event=link?integrations.events.find(item=>item.id===link.remoteId):undefined;return{plan,link,event};}).filter(({plan,event})=>event?eventOnDay(event,day):plan.date===day).sort((a,b)=>(a.event?.startTime??a.plan.startTime??"99:99").localeCompare(b.event?.startTime??b.plan.startTime??"99:99"));
  const goalActions=integrations.links.filter(link=>link.entityKind==="goal"&&link.role==="goal-next-step"&&link.provider==="todoist").map(link=>({link,goal:activeGoals.find(goal=>goal.id===link.entityId),task:integrations.tasks.find(task=>task.id===link.remoteId)})).filter(action=>!!action.goal).sort((a,b)=>Number(b.task?.dueDate===day)-Number(a.task?.dueDate===day)||Number(!!b.task)-Number(!!a.task)||b.link.createdAt.localeCompare(a.link.createdAt));
  let climbingSummary:string|null=null;
  if(daySessions.length){
    const minutes=daySessions.reduce((total,session)=>total+(session.durationMinutes??0),0);const sends=daySessions.reduce((total,session)=>total+sessionSends(session),0);
    if(daySessions.length===1){const session=daySessions[0];climbingSummary=["Session logged",session.venue,session.routine?.title??focusNames[session.focus],session.durationMinutes?`${session.durationMinutes} min`:"",sends?`${sends} ${sends===1?"send":"sends"}`:"",session.healthWorkoutId?"Apple Health linked":""].filter(Boolean).join(" · ");}
    else climbingSummary=[`${daySessions.length} sessions logged`,minutes?`${minutes} min total`:"",sends?`${sends} sends`:""].filter(Boolean).join(" · ");
  }else if(dayPlans.length){
    const {plan,link,event}=dayPlans[0];const time=event?.allDay?"All day":event&&event.startDate<day?"Continues":event?.startTime?clockLabel(event.startTime):plan.startTime?clockLabel(plan.startTime):"Planned";const venue=event?.location||plan.venue;
    climbingSummary=[time,plan.title,venue,link?(event?"Google Calendar":"Calendar event unavailable"):"",dayPlans.length>1?`+${dayPlans.length-1} more`:""].filter(Boolean).join(" · ");
  }else if(goalActions.length){
    const {goal,task}=goalActions[0];climbingSummary=task?["Todoist",task.title,task.dueDate?`Due ${shortDay(task.dueDate)}`:""].filter(Boolean).join(" · "):["Next",goal!.nextStep||goal!.title,"Linked Todoist task is unavailable or no longer active"].join(" · ");
  }else if(activeGoals.length){const goal=activeGoals.find(item=>item.nextStep)||activeGoals[0];climbingSummary=goal.nextStep?`Next · ${goal.nextStep} · ${goal.title}`:`Active goal · ${goal.title}`;}
  const healthSummary=snapshot?.sleepMinutes!=null?`${Math.floor(snapshot.sleepMinutes/60)}h ${Math.round(snapshot.sleepMinutes%60)}m sleep`:snapshot?.restingHeartRate!=null?`${Math.round(snapshot.restingHeartRate)} bpm resting`:snapshot?.steps!=null?`${Math.round(snapshot.steps).toLocaleString()} steps`:null;
  const showHealth=healthSummary!==null;const showClimbing=climbingLoaded&&climbing!==null&&climbingSummary!==null;
  if(!showHealth&&!showClimbing)return null;
  return <section className="life-overview"><h2>Also today</h2>{showHealth&&<button onClick={()=>open("health")}><span>Apple Health</span><strong>{healthSummary}</strong></button>}{showClimbing&&<button aria-label={`Open Climbing. ${climbingSummary}`} onClick={()=>open("climbing")}><span>Climbing</span><strong>{climbingSummary}</strong></button>}</section>;
}

function clockLabel(time:string){const [hour,minute]=time.split(":").map(Number);return `${hour%12||12}:${String(minute).padStart(2,"0")} ${hour<12?"am":"pm"}`;}
function shortDay(day:string){return new Date(`${day}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric"});}
