"use client";
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from "react";
import { CalendarDays, Check, ExternalLink, LoaderCircle, Mail, Plus, RefreshCw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { dateKey, dateFromKey } from "@/lib/workspace";
import { emptySync, eventOnDay, todoistAttentionDate, todoistTaskGroup, PERSONAL_CALENDAR, type IntegrationRelation, type Provider, type SyncProvider, type SyncView, type RemoteTask, type RemoteEvent, type TodoistTaskGroup } from "@/lib/integrations/model";

export type RemoteDraft = {
  provider: Provider;
  item?: RemoteTask | RemoteEvent;
  day: string;
  preset?: { title?: string; date?: string | null; endDate?: string; time?: string; endTime?: string; allDay?: boolean; location?: string };
  link?: Pick<IntegrationRelation, "entityKind" | "entityId" | "role">;
  description?: string;
};
type ProviderMap<T>=Record<SyncProvider,T>;
type IntegrationContextType={view:SyncView;busy:boolean;providerBusy:ProviderMap<boolean>;error:string;providerErrors:ProviderMap<string>;freshness:ProviderMap<string|null>;date:string;setDate:(date:string)=>void;openSettings:()=>void;openEditor:(draft:RemoteDraft)=>void;refresh:()=>Promise<void>;refreshProvider:(provider:SyncProvider,date?:string)=>Promise<void>;reload:()=>Promise<void>;perform:(path:string,body:unknown,provider?:SyncProvider)=>Promise<unknown>};
const IntegrationContext=createContext<IntegrationContextType|null>(null);
export function useIntegrations(){const context=useContext(IntegrationContext);if(!context)throw new Error("Integration provider missing");return context;}
const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
const message=(error:unknown)=>error instanceof Error?error.message:"The connection could not be updated.";
const providerName=(provider:Provider)=>provider==="todoist"?"Todoist":"Google Calendar";
const syncProviderName=(provider:SyncProvider)=>provider==="todoist"?"Todoist":provider==="google"?"Google Calendar":"Gmail";
const providerMap=<T,>(value:T):ProviderMap<T>=>({todoist:value,google:value,gmail:value});
const operationProvider=(path:string,body:unknown):SyncProvider|null=>{
  if(path.startsWith("/gmail/"))return "gmail";
  if(path.startsWith("/todoist/")||path==="/sync/todoist")return "todoist";
  if((path.startsWith("/google/")&&path!=="/google/configure")||path==="/sync/google")return "google";
  if((path==="/mutate"||path==="/disconnect")&&body&&typeof body==="object"&&"provider" in body){const provider=(body as {provider?:unknown}).provider;if(provider==="todoist"||provider==="google"||provider==="gmail")return provider;}
  return null;
};

export function IntegrationProvider({children}:{children:ReactNode}) {
  const [view,setView]=useState<SyncView>(emptySync);
  const etagRef=useRef("");
  const [providerBusy,setProviderBusy]=useState<ProviderMap<boolean>>(()=>providerMap(false));const busyRef=useRef<ProviderMap<boolean>>(providerMap(false));
  const [generalBusy,setGeneralBusy]=useState(false);const generalBusyRef=useRef(false);
  const [providerErrors,setProviderErrors]=useState<ProviderMap<string>>(()=>providerMap(""));const [generalError,setGeneralError]=useState("");const [date,setDate]=useState("");
  const [draft,setDraft]=useState<RemoteDraft|null>(null);
  const opener=useRef<HTMLElement|null>(null);
  const load=useCallback(async()=>{const response=await fetch("/api/integrations",{cache:"no-store",headers:etagRef.current?{"If-None-Match":etagRef.current}:{}});if(response.status===304)return;if(!response.ok)throw new Error("Connections could not be loaded. Your local plans are still available.");setView(await response.json() as SyncView);etagRef.current=response.headers.get("etag")||"";setGeneralError("");},[]);
  useEffect(()=>{const timer=setTimeout(()=>{if(new URLSearchParams(location.search).get("connections")==="1")window.dispatchEvent(new CustomEvent("workspace:open-settings"));void load().catch(err=>setGeneralError(message(err)));},0);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{const update=()=>{if(document.visibilityState==="visible"&&!generalBusyRef.current&&!Object.values(busyRef.current).some(Boolean))void load().catch(()=>{});};const timer=setInterval(update,30_000);window.addEventListener("focus",update);return()=>{clearInterval(timer);window.removeEventListener("focus",update);};},[load]);
  const perform=useCallback(async(path:string,body:unknown,providerOverride?:SyncProvider)=>{
    const provider=providerOverride??operationProvider(path,body);
    if(generalBusyRef.current||(provider?busyRef.current[provider]:Object.values(busyRef.current).some(Boolean)))throw new Error(provider?`Wait for the current ${syncProviderName(provider)} request to finish.`:"Wait for the current sync to finish.");
    if(provider){busyRef.current[provider]=true;setProviderBusy(current=>({...current,[provider]:true}));setProviderErrors(current=>({...current,[provider]:""}));}
    else {generalBusyRef.current=true;setGeneralBusy(true);setGeneralError("");}
    try{const response=await fetch(`/api/integrations${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string}&SyncView;
      if(!response.ok){if(response.status===409)await load().catch(()=>{});throw new Error(result.error||"The service could not apply this change.");}
      if(result.todoist && result.google)setView(result);return result;
    }catch(err){const detail=message(err);if(provider)setProviderErrors(current=>({...current,[provider]:detail}));else setGeneralError(detail);throw err;}finally{if(provider){busyRef.current[provider]=false;setProviderBusy(current=>({...current,[provider]:false}));}else{generalBusyRef.current=false;setGeneralBusy(false);}}
  },[load]);
  const refreshProvider=useCallback(async(provider:SyncProvider,selectedDate?:string)=>{const timeZone=zone();if(provider==="todoist")await perform("/sync/todoist",{timeZone},provider);else if(provider==="google"){const target=selectedDate||date;if(target)await perform("/sync/google",{date:target,timeZone},provider);}else await perform("/gmail/sync",{},provider);},[date,perform]);
  const todoistConnected=view.todoist.connected;const googleConnected=view.google.connected;const gmailConnected=view.gmail.connected;
  const refresh=useCallback(async()=>{const jobs:Promise<void>[]=[];if(todoistConnected)jobs.push(refreshProvider("todoist"));if(googleConnected&&date)jobs.push(refreshProvider("google",date));if(gmailConnected)jobs.push(refreshProvider("gmail"));await Promise.allSettled(jobs);},[date,gmailConnected,googleConnected,refreshProvider,todoistConnected]);
  useEffect(()=>{if(!view.google.connected||!date)return;let retry:ReturnType<typeof setTimeout>|undefined;const attempt=()=>{if(busyRef.current.google||generalBusyRef.current){retry=setTimeout(attempt,500);return;}void refreshProvider("google",date).catch(()=>{});};attempt();return()=>{if(retry)clearTimeout(retry);};},[view.google.connected,date,refreshProvider]);
  const busy=generalBusy||Object.values(providerBusy).some(Boolean);const error=generalError||providerErrors.todoist||providerErrors.google||providerErrors.gmail;
  const draftBusy=draft?providerBusy[draft.provider]:false;
  function captureFocus(){opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;}
  const context={view,busy,providerBusy,error,providerErrors,freshness:{todoist:view.todoist.lastSynced,google:view.google.lastSynced,gmail:view.gmail.lastSynced},date,setDate,refresh,refreshProvider,reload:load,perform,openSettings:()=>{setGeneralError("");window.dispatchEvent(new CustomEvent("workspace:open-settings"));},openEditor:(next:RemoteDraft)=>{captureFocus();setGeneralError("");setDraft(next);}};
  const restoreFocus=(event:Event)=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();else document.getElementById("workspace-settings-nav")?.focus();};
  return <IntegrationContext.Provider value={context}>{children}
    <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!draftBusy){setDraft(null);setGeneralError("");}}}><DialogContent className="editor-dialog" onCloseAutoFocus={restoreFocus} onInteractOutside={event=>event.preventDefault()}>{draft&&<RemoteEditor key={`${draft.provider}:${draft.item?.id||"new"}`} draft={draft} onClose={()=>setDraft(null)}/>}</DialogContent></Dialog>
  </IntegrationContext.Provider>;
}
export function IntegrationSettings() {
  const {view,busy,providerBusy,providerErrors,error,perform,refresh,refreshProvider}=useIntegrations();const [token,setToken]=useState("");const [authUrl,setAuthUrl]=useState("");const [gmailAuthUrl,setGmailAuthUrl]=useState("");const [localError,setLocalError]=useState("");
  const [googleFileState,setGoogleFileState]=useState<"unchanged"|"uploading"|"saved"|"error">("unchanged");
  const connectTodoist=async()=>{setLocalError("");try{await perform("/todoist/connect",{token});setToken("");}catch{}};
  const uploadGoogle=async(file?:File)=>{if(!file)return;setAuthUrl("");setLocalError("");setGoogleFileState("uploading");try{if(file.size>64000)throw new Error("Choose the small Desktop OAuth client JSON file.");let client:unknown;try{client=JSON.parse(await file.text());}catch{throw new Error("This file is not valid JSON. Choose the downloaded Google Desktop app client file.");}await perform("/google/configure",client);setGoogleFileState("saved");}catch(err){setGoogleFileState("error");setLocalError(message(err));}};
  const connectGoogle=async()=>{setAuthUrl("");try{const result=await perform("/google/start",{}) as {url:string};setAuthUrl(result.url);}catch{}};
  const connectGmail=async()=>{setGmailAuthUrl("");try{const result=await perform("/gmail/start",{}) as {url:string};setGmailAuthUrl(result.url);}catch{}};
  const connectedCount=[view.todoist.connected,view.google.connected,view.gmail.connected].filter(Boolean).length;
  const todoistError=providerErrors.todoist||view.todoist.error;const googleError=providerErrors.google||view.google.error;const gmailError=providerErrors.gmail||view.gmail.error;
  return <div className="settings-stack"><div className="settings-section-heading"><div><h2>Planning and mail</h2><p>Personal providers only. Work accounts and the Artek project tree stay excluded.</p></div>{connectedCount>0&&<Button variant="outline" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15} className={busy?"spin":""}/>{busy?"Syncing…":"Sync now"}</Button>}</div>
    <div className="connection-card"><div className="connection-card-heading"><span className="service-symbol todoist-symbol"><Check size={20}/></span><div><h3>Todoist</h3><p>Personal project and its subprojects</p></div><span className={`connection-state ${view.todoist.connected?"connected":""}`}>{view.todoist.connected?"Connected":"Not connected"}</span></div>
      {view.todoist.connected?<><p className="connection-detail">{view.todoist.sources.map(source=>source.name).join(" · ")}</p><p className="connection-detail">{view.todoist.lastSynced?`Last synced ${new Date(view.todoist.lastSynced).toLocaleString()}`:"Ready for the first sync"}</p>{todoistError&&<p className="form-error" role="alert">{todoistError}</p>}<button className="text-button" disabled={providerBusy.todoist} onClick={()=>void refreshProvider("todoist").catch(()=>{})}><RefreshCw size={14} className={providerBusy.todoist?"spin":""}/> {providerBusy.todoist?"Syncing…":"Sync Todoist"}</button><button className="text-button" disabled={providerBusy.todoist} onClick={()=>void perform("/disconnect",{provider:"todoist"}).catch(()=>{})}>Disconnect Todoist</button></>:<><p className="connection-detail">Paste your personal API token from <a href="https://app.todoist.com/app/settings/integrations/developer" target="_blank" rel="noreferrer">Todoist’s developer settings <ExternalLink size={12}/></a>. It stays on this Mac. This enables creating, editing, completing, and deleting tasks in Personal.</p><label className="connection-label" htmlFor="todoist-token">Todoist API token</label><div className="token-row"><Input id="todoist-token" type="password" autoComplete="off" value={token} disabled={busy} onChange={e=>setToken(e.target.value)}/><Button disabled={busy||token.trim().length<20} onClick={()=>void connectTodoist()}>Connect</Button></div><p className="connection-detail">A Personal project must exist. The Inbox and Artek project tree are excluded.</p></>}
    </div>
    <div className="connection-card"><div className="connection-card-heading"><span className="service-symbol calendar-symbol"><CalendarDays size={20}/></span><div><h3>Google Calendar</h3><p>{PERSONAL_CALENDAR}</p></div><span className={`connection-state ${view.google.connected?"connected":""}`}>{view.google.connected?"Connected":"Not connected"}</span></div>
      {view.google.connected?<><p className="connection-detail">{view.google.lastSynced?`Last synced ${new Date(view.google.lastSynced).toLocaleString()}`:"Ready for the first sync"}</p>{googleError&&<p className="form-error" role="alert">{googleError}</p>}<button className="text-button" disabled={providerBusy.google} onClick={()=>void refreshProvider("google").catch(()=>{})}><RefreshCw size={14} className={providerBusy.google?"spin":""}/> {providerBusy.google?"Syncing…":"Sync Calendar"}</button><button className="text-button" disabled={providerBusy.google} onClick={()=>void perform("/disconnect",{provider:"google"}).catch(()=>{})}>Disconnect Google Calendar</button></>:<><p className="connection-detail">Use a <a href="https://developers.google.com/workspace/calendar/api/quickstart/nodejs" target="_blank" rel="noreferrer">Google Desktop OAuth client <ExternalLink size={12}/></a> in a dedicated personal Google Cloud project with Calendar API enabled. Set Google Auth Platform’s audience to External and add {PERSONAL_CALENDAR} as a test user while in Testing. Choose its downloaded JSON file, then authorize your Gmail account in your browser.</p><p className="connection-detail">Seeing “403: org_internal”? The Google app has an Internal audience, which blocks personal Gmail accounts. <a href="https://support.google.com/cloud/answer/15549945" target="_blank" rel="noreferrer">Review its audience settings <ExternalLink size={12}/></a>, then connect again. If the client belongs to a shared Artek app, use a separate personal project and upload its client file here.</p><label className="connection-label" htmlFor="google-client">Google OAuth client file</label><input id="google-client" type="file" accept=".json,application/json" disabled={busy} onChange={e=>void uploadGoogle(e.target.files?.[0])}/>{googleFileState==="saved"&&<p className="connection-detail" role="status">Desktop client file saved. Connect below to authorize this client.</p>}{googleFileState==="error"&&<p className="form-error" role="alert">The selected file was not saved. Upload a valid Desktop app client file before connecting.</p>}<Button className="google-connect" disabled={busy||!view.google.configured||googleFileState==="uploading"||googleFileState==="error"} onClick={()=>void connectGoogle()}>Connect Google Calendar</Button>{authUrl&&<p className="connection-detail">Finish authorization in your default browser. <a href={authUrl} target="_blank" rel="noreferrer">Open authorization again</a></p>}<p className="connection-detail">Sign in as {PERSONAL_CALENDAR}. A Google app left in Testing may need reconnection after 7 days.</p></>}
    </div>
    <div className="connection-card"><div className="connection-card-heading"><span className="service-symbol gmail-symbol"><Mail size={20}/></span><div><h3>Gmail</h3><p>{view.gmail.account||PERSONAL_CALENDAR}</p></div><span className={`connection-state ${view.gmail.connected?"connected":""}`}>{view.gmail.connected?"Connected":"Not connected"}</span></div>
      {view.gmail.connected?<><p className="connection-detail">{view.gmail.unreadCount} unread in the recent inbox view{view.gmail.lastSynced?` · Last synced ${new Date(view.gmail.lastSynced).toLocaleString()}`:""}</p><p className="connection-detail">Workspace can read mail, compose and send, and move messages to Gmail Trash. It never permanently erases mail.</p>{gmailError&&<p className="form-error" role="alert">{gmailError}</p>}<button className="text-button" disabled={providerBusy.gmail} onClick={()=>void refreshProvider("gmail").catch(()=>{})}><RefreshCw size={14} className={providerBusy.gmail?"spin":""}/> {providerBusy.gmail?"Syncing…":"Sync Gmail"}</button><button className="text-button" disabled={providerBusy.gmail} onClick={()=>void perform("/disconnect",{provider:"gmail"}).catch(()=>{})}>Disconnect Gmail</button></>:<><p className="connection-detail">Enable the <a href="https://developers.google.com/workspace/gmail/api/quickstart/nodejs" target="_blank" rel="noreferrer">Gmail API <ExternalLink size={12}/></a> in the same personal Google Cloud project, then reuse the Google OAuth client uploaded above. Workspace will accept only {PERSONAL_CALENDAR}.</p><p className="connection-detail">Google’s Gmail modify permission covers reading mail, composing and sending, and moving messages to Trash. Workspace does not permanently erase messages or send anything without your final Send click.</p><Button className="google-connect" disabled={busy||!view.gmail.configured} onClick={()=>void connectGmail()}>Connect Gmail</Button>{gmailAuthUrl&&<p className="connection-detail">Finish authorization in your default browser. <a href={gmailAuthUrl} target="_blank" rel="noreferrer">Open authorization again</a></p>}{!view.gmail.configured&&<p className="connection-detail">Upload a Google Desktop OAuth client in the Google Calendar card first.</p>}</>}
    </div>
    <p className="connection-detail">Workspace can edit solo calendar events. Meetings with guests stay in Google Calendar. Local priorities and notes remain local until you create an item in a connected app.</p>
    {localError&&<p className="form-error" role="alert">{localError}</p>}{error&&![todoistError,googleError,gmailError].includes(error)&&<p className="form-error" role="alert">{error}</p>}
    <p className="sync-caption">Two-way sync where supported · Refreshes every five minutes while Workspace is open</p>
  </div>;
}
export function TodoistTasks({day,area,mode="day"}:{day:string;area:string;mode?:"day"|"all"}) {
  const {view,providerBusy,openEditor,openSettings,perform}=useIntegrations();const busy=providerBusy.todoist;if(area==="independent")return null;
  if(!view.todoist.connected)return mode==="all"?<section className="life-empty"><Check size={30}/><h2>Bring in your Personal tasks.</h2><p>Connect Todoist from Settings to see due dates, deadlines, and unscheduled tasks here.</p><Button onClick={openSettings}>Open Settings</Button></section>:null;
  const climbingTaskIds=new Set(view.links.filter(link=>link.provider==="todoist").map(link=>link.remoteId));
  const today=dateKey(new Date());
  const row=(task:RemoteTask)=>{const attentionDate=todoistAttentionDate(task);return <div className="remote-task-row" key={task.id}><button className="check-button" disabled={busy||!!view.todoist.error} aria-label={`Complete ${task.title} in Todoist`} onClick={()=>void perform("/mutate",{provider:"todoist",action:"complete",id:task.id,version:task.version,anchorDate:day,requestId:crypto.randomUUID(),timeZone:zone()}).catch(()=>{})}/><button className="remote-task-title" disabled={busy} onClick={()=>openEditor({provider:"todoist",item:task,day})}><strong>{task.title}</strong><span>{task.sourceName}{climbingTaskIds.has(task.id)?" · Climbing":""}{attentionDate&&attentionDate<today?` · Overdue ${attentionDate}`:""}{task.dueTime?` · ${task.dueTime}`:""}{task.recurring?" · Recurring":""}{task.deadline?` · Deadline ${task.deadline}`:""}</span></button><a href={task.url} target="_blank" rel="noreferrer" aria-label={`Open ${task.title} in Todoist`}><ExternalLink size={15}/></a></div>;};
  if(mode==="all"){
    const groups:{key:TodoistTaskGroup;label:string;tasks:RemoteTask[]}[]=[{key:"overdue",label:"Overdue",tasks:[]},{key:"today",label:"Today",tasks:[]},{key:"deadlines",label:"Deadlines",tasks:[]},{key:"upcoming",label:"Upcoming",tasks:[]},{key:"no-date",label:"No date",tasks:[]}];
    for(const task of view.tasks)groups.find(group=>group.key===todoistTaskGroup(task,today))!.tasks.push(task);
    for(const group of groups)group.tasks.sort((a,b)=>(a.dueDate||a.deadline||"9999").localeCompare(b.dueDate||b.deadline||"9999")||(a.dueTime||"").localeCompare(b.dueTime||"")||b.priority-a.priority||a.title.localeCompare(b.title));
    const visible=groups.filter(group=>group.tasks.length);
    if(!visible.length)return <section className="agenda-panel remote-tasks"><div className="section-heading"><div><h2>Todoist Personal</h2><p>No active tasks</p></div><button className="text-button" disabled={busy||!!view.todoist.error} onClick={()=>openEditor({provider:"todoist",day})}><Plus size={16}/> Add task</button></div><p className="remote-empty">Your Personal task list is clear.</p></section>;
    return <div className="day-column">{visible.map((group,index)=><section key={group.label} className="agenda-panel remote-tasks"><div className="section-heading"><div><h2>{group.label}</h2><p>Personal · {group.tasks.length} {group.tasks.length===1?"task":"tasks"}</p></div>{index===0&&<button className="text-button" disabled={busy||!!view.todoist.error} onClick={()=>openEditor({provider:"todoist",day})}><Plus size={16}/> Add task</button>}</div><div className="remote-task-list">{group.tasks.map(row)}</div></section>)}</div>;
  }
  const tasks=view.tasks.filter(task=>{const attentionDate=todoistAttentionDate(task);return attentionDate===day||(day===today&&!!attentionDate&&attentionDate<day);}).sort((a,b)=>(todoistAttentionDate(a)||"").localeCompare(todoistAttentionDate(b)||"")||b.priority-a.priority);
  return <section className="agenda-panel remote-tasks"><div className="section-heading"><div><h2>From Todoist</h2><p>Personal · {tasks.length} {tasks.length===1?"task":"tasks"}</p></div><button className="text-button" disabled={busy||!!view.todoist.error} onClick={()=>openEditor({provider:"todoist",day})}><Plus size={16}/> Add task</button></div>{tasks.length?<div className="remote-task-list">{tasks.map(row)}</div>:<p className="remote-empty">No Todoist tasks need attention on this day.</p>}</section>;
}
export function GoogleEvents({day,area}:{day:string;area:string}) {
  const {view,providerBusy,openEditor}=useIntegrations();const busy=providerBusy.google;if(!view.google.connected||area==="independent")return null;
  const climbingEventIds=new Set(view.links.filter(link=>link.provider==="google").map(link=>link.remoteId));
  const events=view.events.filter(event=>eventOnDay(event,day)).sort((a,b)=>Number(b.allDay)-Number(a.allDay)||(a.startTime||"").localeCompare(b.startTime||""));
  return <div className="google-events"><div className="google-events-heading"><span><CalendarDays size={15}/> Google Calendar</span><button className="text-button" disabled={busy||!!view.google.error} onClick={()=>openEditor({provider:"google",day})}><Plus size={15}/> Add event</button></div>{events.length?events.map(event=><div className="plan-row" key={`${event.sourceId}:${event.id}`}><div className="plan-time"><strong>{event.allDay?"All day":event.startDate<day?"Continues":event.startTime}</strong>{!event.allDay&&<span>{event.endDate>day?"Next day":event.endTime}</span>}</div><button className="plan-content" disabled={busy} onClick={()=>openEditor({provider:"google",item:event,day})}><strong>{event.title}</strong><span className="remote-event-meta">{event.location||"Personal calendar"}{climbingEventIds.has(event.id)?" · Climbing":""}{event.recurring?" · This occurrence":""}</span></button><a className="remote-link" href={event.url} target="_blank" rel="noreferrer" aria-label={`Open ${event.title} in Google Calendar`}><ExternalLink size={15}/></a></div>):<p className="remote-empty">No calendar events for this day.</p>}</div>;
}
function RemoteEditor({draft,onClose}:{draft:RemoteDraft;onClose:()=>void}) {
  const {view,providerBusy,providerErrors,perform}=useIntegrations();const busy=providerBusy[draft.provider];const error=providerErrors[draft.provider]||view[draft.provider].error||"";const item=draft.item;const task=draft.provider==="todoist"?item as RemoteTask|undefined:undefined;const event=draft.provider==="google"?item as RemoteEvent|undefined:undefined;
  const [title,setTitle]=useState(item?.title||draft.preset?.title||"");const [date,setDate]=useState(task?task.dueDate||"":event?.startDate||draft.preset?.date||draft.day);
  const [endDate,setEndDate]=useState(event?.endDate||draft.preset?.endDate||draft.preset?.date||draft.day);const [time,setTime]=useState(event?.startTime||draft.preset?.time||"09:00");const [endTime,setEndTime]=useState(event?.endTime||draft.preset?.endTime||"10:00");const [allDay,setAllDay]=useState(event?.allDay??draft.preset?.allDay??false);const [location,setLocation]=useState(event?.location||draft.preset?.location||"");
  const [sourceId,setSourceId]=useState(task?.sourceId||view.todoist.sources.find(s=>/^personal$/i.test(s.name.trim()))?.id||"");
  const [confirmDelete,setConfirmDelete]=useState(false);const [localError,setLocalError]=useState("");const request=useRef({id:crypto.randomUUID(),payload:""});
  const editable=draft.provider==="todoist"||!event||event.editable;
  async function submit(action:"create"|"update"|"delete") {
    setLocalError("");
    const body={provider:draft.provider,action,anchorDate:draft.day,...(item?{id:item.id,version:item.version}:{}),timeZone:zone(),...(action!=="delete"?{title,date:date||null,...(draft.provider==="todoist"?{sourceId}:{endDate,time:allDay?null:time,endTime:allDay?null:endTime,allDay,location}),...(action==="create"&&draft.link?{link:draft.link}:{})}:{})};
    const serialized=JSON.stringify(body);if(request.current.payload&&request.current.payload!==serialized)request.current={id:crypto.randomUUID(),payload:serialized};else request.current.payload=serialized;
    try{await perform("/mutate",{...body,requestId:request.current.id});onClose();}catch(err){setLocalError(message(err));}
  }
  function changeAllDay(value:boolean){setAllDay(value);if(value&&endDate<=date){const next=dateFromKey(date);next.setDate(next.getDate()+1);setEndDate(dateKey(next));}}
  return <><DialogTitle>{item?"Edit":"Add to"} {providerName(draft.provider)}</DialogTitle><DialogDescription>{draft.description|| (draft.provider==="todoist"?"Changes save to your Personal project in Todoist.":event?.recurring?"Changes apply only to this occurrence in your personal calendar.":"Changes save to your personal Gmail calendar.")}</DialogDescription>
    {!editable?<div className="remote-readonly"><h3>{event?.title}</h3><p>This event has guests, belongs to another organizer, or uses a special calendar format. Edit it in Google Calendar to manage those details.</p><a href={event?.url} target="_blank" rel="noreferrer">Open in Google Calendar <ExternalLink size={15}/></a><Button variant="outline" onClick={onClose}>Close</Button></div>:<form className="editor-form" onSubmit={e=>{e.preventDefault();void submit(item?"update":"create");}}>
      <label htmlFor="remote-title">Title</label><textarea id="remote-title" autoFocus rows={3} required maxLength={2000} value={title} disabled={busy} onChange={e=>setTitle(e.target.value)}/>
      {draft.provider==="todoist"?<><div className="form-row"><div><label htmlFor="remote-project">Project</label><select id="remote-project" value={sourceId} disabled={busy||!!item} onChange={e=>setSourceId(e.target.value)}>{view.todoist.sources.map(source=><option key={source.id} value={source.id}>{source.name}</option>)}</select></div><div><label htmlFor="remote-date">Due date <span className="optional">(optional)</span></label><Input id="remote-date" type="date" disabled={busy||task?.recurring||!!task?.dueTime} value={date} onChange={e=>setDate(e.target.value)}/></div></div>{task?.recurring&&<p className="connection-detail">Edit recurrence and due dates in Todoist. Completing this task advances to its next occurrence.</p>}{task?.dueTime&&<p className="connection-detail">Change the date and time in Todoist to preserve its time zone and reminders. Title edits work here.</p>}</>:<><label className="all-day-control"><input type="checkbox" checked={allDay} disabled={busy} onChange={e=>changeAllDay(e.target.checked)}/> All-day event</label><div className="form-row"><div><label htmlFor="remote-date">Starts on</label><Input id="remote-date" required type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></div><div><label htmlFor="remote-end-date">{allDay?"Ends before":"Ends on"}</label><Input id="remote-end-date" required type="date" value={endDate} disabled={busy} onChange={e=>setEndDate(e.target.value)}/></div></div>{allDay?<p className="connection-detail">The end date is exclusive. For one day, choose the following date.</p>:<div className="form-row"><div><label htmlFor="remote-start">Start time</label><Input id="remote-start" required type="time" value={time} disabled={busy} onChange={e=>setTime(e.target.value)}/></div><div><label htmlFor="remote-end">End time</label><Input id="remote-end" required type="time" value={endTime} disabled={busy} onChange={e=>setEndTime(e.target.value)}/></div></div>}<label htmlFor="remote-location">Location <span className="optional">(optional)</span></label><Input id="remote-location" maxLength={1000} value={location} disabled={busy} onChange={e=>setLocation(e.target.value)}/><p className="connection-detail">Times use {zone()}. Events created here have no guests.</p></>}
      {(localError||error)&&<p className="form-error" role="alert">{localError||error}</p>}
      {confirmDelete&&<div className="form-error">Delete this {draft.provider==="todoist"?"task":event?.recurring?"occurrence":"event"} from {providerName(draft.provider)}? This also removes it from the source app.{draft.provider === "todoist" ? " Todoist also deletes any completed subtasks belonging to this task." : ""}<div className="delete-confirm"><Button variant="outline" type="button" disabled={busy} onClick={()=>setConfirmDelete(false)}>Keep it</Button><Button variant="destructive" type="button" disabled={busy} onClick={()=>void submit("delete")}>Delete from {draft.provider==="todoist"?"Todoist":"Calendar"}</Button></div></div>}
      <div className="editor-actions">{item&&<button className="delete-button" type="button" disabled={busy} onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/> Delete</button>}<div><Button variant="ghost" type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy||!title.trim()}>{busy?<><LoaderCircle className="spin" size={15}/> Saving…</>:"Save to app"}</Button></div></div>
    </form>}
  </>;
}
