"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Moon, SlidersHorizontal, RefreshCw, NotebookPen, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { average, buildNights, emptySleep, hasSleepCoverage, localDay, median, minutesText, nightFlags, shiftDay, sleepEpisodes, sleepSources, type SleepArchive, type SleepContext, type SleepNight, type SleepNote, type SleepSettings } from "@/lib/sleep";

const stageLabels = { awake: "Awake", rem: "REM", core: "Core", deep: "Deep", asleep: "Unspecified sleep", unknown: "Unknown" };
const stages = ["awake", "rem", "core", "deep", "asleep", "unknown"] as const;
const noteTags = ["caffeine", "medication", "alcohol", "stress", "nap", "late meal", "temperature", "illness", "night sweats", "exercise"] as const;
const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
const clockTime = (time: number, zone: string) => new Date(time).toLocaleTimeString("en-US", { timeZone: zone, hour: "numeric", minute: "2-digit" });
type Draft = Pick<SleepNote, "date" | "revision" | "text" | "tags">;

export function SleepPanel({ active = true, openSetup }: { active?: boolean; openSetup: () => void }) {
  const [archive, setArchive] = useState<SleepArchive>(emptySleep), [loaded, setLoaded] = useState(false), [error, setError] = useState("");
  const [day, setDay] = useState(""), [range, setRange] = useState(30), [settingsOpen, setSettingsOpen] = useState(false), [saving, setSaving] = useState(false);
  const [drafts, setDrafts] = useState<Record<string, Draft>>({}), [noteMessage, setNoteMessage] = useState(""), [noteError, setNoteError] = useState("");
  const [feedbackDate, setFeedbackDate] = useState("");
  const [clock, setClock] = useState(Date.now);
  const mutationEpoch = useRef(0), loadSequence = useRef(0);
  const load = useCallback(async () => { const epoch = mutationEpoch.current, sequence = ++loadSequence.current; const response = await fetch("/api/health/sleep", { cache: "no-store" }); const data = await response.json() as SleepArchive & { error?: string }; if (!response.ok) throw new Error(data.error); if (epoch !== mutationEpoch.current || sequence !== loadSequence.current) return; setArchive(data); setLoaded(true); setError(""); setClock(Date.now()); }, []);
  useEffect(() => { if (!active) return; const initial = setTimeout(() => void load().catch(e => setError(e.message)), 0); const timer = setInterval(() => { if (document.visibilityState === "visible") void load().catch(e => setError(e.message)); }, 30000); return () => { clearTimeout(initial); clearInterval(timer); }; }, [active, load]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (Object.keys(drafts).length) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [drafts]);
  const sources = useMemo(() => sleepSources(archive.samples), [archive.samples]);
  const sourceId = archive.settings.sourceId ?? sources[0]?.id ?? "";
  const source = sources.find(s => s.id === sourceId);
  const nights = useMemo(() => buildNights(archive.samples, sourceId, archive.timeZone, archive.ranges), [archive.samples, archive.timeZone, archive.ranges, sourceId]);
  const currentDay = localDay(clock, archive.timeZone);
  const selectedDay = day || nights.at(-1)?.date || currentDay;
  const night = nights.find(n => n.date === selectedDay);
  const rangeFrom = shiftDay(selectedDay, 1 - range);
  const visible = useMemo(() => nights.filter(n => n.date >= rangeFrom && n.date <= selectedDay), [nights, rangeFrom, selectedDay]);
  const baseline = nights.filter(n => n.date >= shiftDay(rangeFrom, -28) && n.date < rangeFrom);
  const comparable = visible.filter(hasSleepCoverage), comparableBaseline = baseline.filter(hasSleepCoverage);
  const comparisonReady = comparable.length >= 7 && comparableBaseline.length >= 7;
  const medianSleep = median(comparable.map(n => n.asleep)), medianAwake = median(comparable.flatMap(n => n.awake == null ? [] : [n.awake]));
  const sleepChange = comparisonReady ? medianSleep! - median(comparableBaseline.map(n => n.asleep))! : null;
  const awakeBaseline = comparableBaseline.flatMap(n => n.awake == null ? [] : [n.awake]), awakeCurrent = comparable.flatMap(n => n.awake == null ? [] : [n.awake]);
  const awakeChange = awakeBaseline.length >= 7 && awakeCurrent.length >= 7 ? medianAwake! - median(awakeBaseline)! : null;
  const episodes = useMemo(() => sleepEpisodes(nights, archive.settings), [nights, archive.settings]);
  const recordedNote = archive.notes.find(n => n.date === selectedDay);
  const note = drafts[selectedDay] || recordedNote || { date: selectedDay, revision: 0, text: "", tags: [] };
  function editNote(changes: Partial<Draft>) { setDrafts(old => ({ ...old, [selectedDay]: { ...note, ...changes } })); setNoteMessage(""); setNoteError(""); }
  async function post<T>(path: string, body: unknown) { mutationEpoch.current++; try { const response = await fetch(`/api/health/sleep/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(result.error); return result; } finally { mutationEpoch.current++; } }
  async function saveSettings(settings: SleepSettings, revision = archive.settingsRevision) { setSaving(true); try { const result = await post<{ settings: SleepSettings; settingsRevision: number }>("settings", { ...settings, revision }); setArchive(a => ({ ...a, settings: result.settings, settingsRevision: result.settingsRevision })); setSettingsOpen(false); setError(""); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  async function saveNote() { const date = selectedDay, pending = { date: note.date, revision: note.revision, text: note.text, tags: note.tags }; setSaving(true); setFeedbackDate(date); setNoteError(""); try { const result = await post<{ note: SleepNote }>("note", pending); setArchive(a => ({ ...a, notes: [...a.notes.filter(n => n.date !== date), result.note] })); setDrafts(a => { const copy = { ...a }; delete copy[date]; return copy; }); setNoteMessage("Saved on this Mac."); } catch (e) { setNoteError((e as Error).message); } finally { setSaving(false); } }
  return <div className="sleep-panel">
    <div className="sleep-heading"><div><p className="eyebrow">SLEEP</p><h2>Understand your nights.</h2><p>Sleep, wakefulness, and the context around them.</p></div><div className="sleep-actions"><Button variant="outline" onClick={() => void load().catch(e => setError(e.message))}><RefreshCw size={15}/> Refresh</Button><Button variant="outline" onClick={() => setSettingsOpen(true)}><SlidersHorizontal size={15}/> Comparison settings</Button></div></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    {!loaded && !error && <p role="status" className="life-muted">Loading sleep history…</p>}
    {loaded && !archive.generatedAt && <section className="sleep-onboarding"><Moon size={27}/><div><h3>Bring the whole night into view.</h3><p>Your existing daily totals don’t contain sleep stages or awakenings. Run the updated iPhone companion, review Health permissions, and tap <strong>Sync now</strong>. Use <strong>Import sleep history</strong> on your phone for earlier nights.</p><Button variant="outline" onClick={openSetup}>Open iPhone setup</Button></div></section>}
    {loaded && archive.generatedAt && <>
      <div className="sleep-controls"><label>Sleep source<select value={sourceId} disabled={saving} onChange={e => void saveSettings({ ...archive.settings, sourceId: e.target.value })}>{!source && <option value={sourceId}>Selected source has no accessible records</option>}{sources.map(s => <option key={s.id} value={s.id}>{s.name} · {localDay(s.first, archive.timeZone)} – {localDay(s.last, archive.timeZone)}</option>)}</select></label><label>Waking date<div className="sleep-date"><Button aria-label="Previous night" variant="outline" onClick={() => { setDay(shiftDay(selectedDay, -1)); setNoteMessage(""); }}><ChevronLeft size={17}/></Button><Input aria-label="Waking date" type="date" value={selectedDay} onChange={e => { if (e.target.value) setDay(e.target.value); setNoteMessage(""); }}/><Button aria-label="Next night" variant="outline" disabled={selectedDay >= currentDay} onClick={() => { setDay(shiftDay(selectedDay, 1)); setNoteMessage(""); }}><ChevronRight size={17}/></Button></div></label><label>Trend window<select value={range} onChange={e => setRange(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></label></div>
      <p className="sleep-provenance">{source ? `${source.name} · ` : ""}{archive.timeZone} · Updated {new Date(archive.generatedAt).toLocaleString()}{archive.settings.sourceId === null && source ? " · Source initially chosen for the most stage records" : ""}</p>
      {night ? <>
        <div className="sleep-metrics"><Metric title="Time asleep" value={minutesText(night.asleep)} detail={`${clockTime(night.start, archive.timeZone)} – ${clockTime(night.end, archive.timeZone)}${!hasSleepCoverage(night) ? " · Partial coverage" : ""}`}/><Metric title="Recorded awake" value={minutesText(night.awake)} detail={night.awakenings == null ? "Wake tracking unavailable" : `${night.awakenings} awakenings of 5+ minutes`}/><Metric title="Recorded sleep share" value={night.share == null ? "—" : `${night.share.toFixed(0)}%`} detail={night.share == null ? "Needs more complete stage coverage" : "Asleep ÷ recorded session span"}/><Metric title="Longest recorded awakening" value={minutesText(night.longestAwake)} detail={`${minutesText(night.unknown)} of unknown intervals`}/></div>
        <section className="sleep-card"><div className="sleep-card-heading"><div><h3>Sleep ending {dateLabel(selectedDay)}</h3><p>Main session · {nightFlags(night, archive.settings).fragmented ? "Above your fragmentation threshold" : nightFlags(night, archive.settings).short ? "Below your sleep-duration threshold" : !hasSleepCoverage(night) ? "Partial coverage; classification unavailable" : night.awake == null ? "Sleep duration recorded; wake tracking unavailable" : "Within your selected thresholds"}</p></div></div><NightTimeline night={night} zone={archive.timeZone}/>{night.boundary && <p className="life-muted">This session is near an imported range boundary. Import adjacent dates before comparing its duration.</p>}{night.otherSleep > 0 && <p className="life-muted">Another {minutesText(night.otherSleep)} recorded in separate sessions ending this day; excluded from the main-night comparison.</p>}</section>
      </> : <section className="sleep-card sleep-missing"><Moon size={25}/><h3>No measured sleep for {dateLabel(selectedDay)}</h3><p>This source has no usable sleep session ending on this date. In-bed-only records and missing or unavailable readings aren’t counted as sleep.</p></section>}
      <section className="sleep-card"><div className="sleep-card-heading"><div><h3>Your sleep over time</h3><p>{dateLabel(rangeFrom)} – {dateLabel(selectedDay)} · {visible.length} of {range} nights recorded</p></div><div className="sleep-legend"><span><i className="sleep-core"/> Asleep</span><span><i className="sleep-awake"/> Awake</span><span><i className="sleep-unknown"/> Missing</span></div></div><Trend nights={visible} from={rangeFrom} count={range} selectedDay={selectedDay} select={setDay}/><div className="sleep-comparisons"><Metric title="Median time asleep" value={minutesText(medianSleep)} detail={sleepChange == null ? "At least 7 nights in each window needed" : `${Math.abs(Math.round(sleepChange))} min ${sleepChange >= 0 ? "more" : "less"} than the prior baseline`}/><Metric title="Median recorded awake" value={minutesText(medianAwake)} detail={awakeChange == null ? `${awakeCurrent.length} nights with wake tracking; 7 per window needed` : `${Math.abs(Math.round(awakeChange))} min ${awakeChange >= 0 ? "more" : "less"} than the prior baseline`}/><Metric title="Nights above fragmentation threshold" value={`${comparable.filter(n => nightFlags(n, archive.settings).fragmented).length} / ${awakeCurrent.length}`} detail="Only nights with sufficient coverage and wake tracking"/></div><p className="life-muted">Baseline: {dateLabel(shiftDay(rangeFrom, -28))} – {dateLabel(shiftDay(rangeFrom, -1))}, using the same source. {comparableBaseline.length}/28 baseline nights with sufficient coverage; {awakeBaseline.length} with wake tracking. {comparable.length}/{visible.length} measured nights qualify in the selected window. Missing nights and sessions with more than 5% unknown time are excluded from medians.</p></section>
      <div className="sleep-two-column"><section className="sleep-card"><h3>Timing & consistency</h3><Timing nights={visible} zone={archive.timeZone}/><p className="life-muted">Recorded sleep onset and final sleep end; these don’t establish bedtime, time in bed, or time to fall asleep.</p></section><section className="sleep-card"><h3>Runs of fragmented nights</h3><p className="life-muted">Two or more consecutive waking dates above your thresholds. A missing night breaks a run.</p>{episodes.length ? <div className="sleep-episodes">{episodes.slice(0, 6).map(e => <button key={e.from} onClick={() => setDay(e.to)}><span>{dateLabel(e.from)} – {dateLabel(e.to)}<small>{e.nights.length} consecutive recorded nights</small></span><strong>{minutesText(average(e.nights.flatMap(n => n.awake == null ? [] : [n.awake])))}<small>avg. awake</small></strong></button>)}</div> : <p className="sleep-empty-text">No consecutive runs in this source’s imported history.</p>}</section></div>
      <section className="sleep-card"><h3>What came before the night</h3><p className="life-muted">Calendar-day context for {dateLabel(shiftDay(selectedDay, -1))}, compared with the preceding 28 days. These are descriptive differences, not evidence of a cause. Health’s daily quantities may combine sources.</p><ContextGrid days={archive.days} day={shiftDay(selectedDay, -1)}/></section>
      <section className="sleep-card"><h3>When you were awake</h3><p className="life-muted">Recorded awake minutes across this {range}-day window, normalized by nights observed in each clock hour. Only observed portions contribute; coverage varies by hour.</p><AwakeHours nights={visible} zone={archive.timeZone}/></section>
    </>}
    <section className="sleep-card sleep-diary"><div className="sleep-card-heading"><div><h3><NotebookPen size={19}/> Notes for {dateLabel(selectedDay)}</h3><p>Your own observations, stored on this Mac. Include times when useful.</p></div>{Object.keys(drafts).length > 0 && <span className="sleep-unsaved">{Object.keys(drafts).length} unsaved {Object.keys(drafts).length === 1 ? "note" : "notes"}</span>}</div>{!archive.generatedAt && <label className="sleep-note-date">Waking date<Input type="date" aria-label="Observation waking date" value={selectedDay} onChange={e => { if(e.target.value) setDay(e.target.value); }}/></label>}<div className="sleep-tags">{noteTags.map(tag => <label key={tag}><input type="checkbox" disabled={saving} checked={note.tags.includes(tag)} onChange={e => editNote({ tags: e.target.checked ? [...note.tags, tag] : note.tags.filter(t => t !== tag) })}/>{tag}</label>)}</div><label className="sr-only" htmlFor="sleep-note">Sleep context and observations</label><Textarea id="sleep-note" value={note.text} maxLength={5000} disabled={saving} onChange={e => editNote({ text: e.target.value })} placeholder="How did sleep feel? Caffeine or medication timing, stress, room temperature, awakenings, or anything that changed…"/><div className="sleep-note-actions"><Button onClick={() => void saveNote()} disabled={saving || !drafts[selectedDay]}>Save note</Button>{drafts[selectedDay] && <Button variant="ghost" disabled={saving} onClick={() => { if (window.confirm("Discard your unsaved text and load the saved note for this date?")) { setDrafts(a => { const copy = { ...a }; delete copy[selectedDay]; return copy; }); setNoteError(""); void load().catch(e => setError(e.message)); } }}>Discard unsaved changes</Button>}<span role="status">{(feedbackDate === selectedDay ? noteMessage : "") || (recordedNote ? `Last saved ${new Date(recordedNote.updatedAt).toLocaleString()}` : "No observations saved for this night.")}</span></div>{noteError && feedbackDate === selectedDay && <p className="form-error" role="alert">{noteError}</p>}</section>
    <details className="sleep-method"><summary>How to read this view</summary><p>Records stay separated by source and device model. The longest sleep session ending on a date is its main night; records up to 3 hours apart are grouped, with a 20-hour maximum span; longer conflicting spans are excluded. Nights within 3 hours of an import boundary are marked partial until adjacent history is available. Other sessions are shown separately. Unknown intervals stay unknown; overlapping conflicting stages are marked unknown. In-bed records are retained but never added to sleep totals.</p><p>All clock times use {archive.timeZone}, the iPhone’s reporting timezone at its latest sleep sync. Original timezone metadata is retained when available; travel can shift historical clock times in this view. Durations use elapsed time, including daylight-saving changes.</p><p>Recorded sleep share is time asleep divided by the span between first and last recorded sleep. It is hidden when unknown time exceeds 5% or wake tracking is unavailable. It is not clinical sleep efficiency. Thresholds are personal pattern-finding settings, not medical cutoffs. Wearables don’t establish a diagnosis or rule out a sleep disorder.</p><p>Daily context is a daily average for resting heart rate, HRV, respiratory rate, and oxygen saturation; steps, energy, and exercise are totals. Missing readings mean no accessible data, which may include permission limitations. Historic deletions or corrections update when that range is imported again.</p><p><a href="https://developer.apple.com/documentation/healthkit/hkcategoryvaluesleepanalysis" target="_blank" rel="noreferrer">Apple’s sleep-record definitions</a></p>{archive.ranges.length > 0 && <p>Imported ranges: {archive.ranges.map(r => `${dateLabel(localDay(r.from, archive.timeZone))} – ${dateLabel(localDay(Date.parse(r.to) - 1, archive.timeZone))}`).join("; ")}. Coverage describes queried dates, not a guarantee of measured nights.</p>}</details>
    <Dialog open={settingsOpen} onOpenChange={open => !saving && setSettingsOpen(open)}><DialogContent className="editor-dialog"><DialogTitle>Sleep comparisons</DialogTitle><DialogDescription>Personal thresholds for exploring patterns. These are not diagnostic criteria.</DialogDescription><SettingsEditor key={String(settingsOpen)} settings={archive.settings} revision={archive.settingsRevision} saving={saving} save={saveSettings}/>{error && <p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
  </div>;
}

function Metric({ title, value, detail }: { title: string; value: string; detail: string }) { return <article className="sleep-metric"><span>{title}</span><strong>{value}</strong><p>{detail}</p></article>; }
function NightTimeline({ night, zone }: { night: SleepNight; zone: string }) {
  const span = night.end - night.start;
  return <><div className="sleep-hypnogram" role="img" aria-label={`Sleep stages from ${clockTime(night.start, zone)} to ${clockTime(night.end, zone)}. ${minutesText(night.asleep)} asleep, ${minutesText(night.awake)} recorded awake, ${minutesText(night.unknown)} unknown.`}>{stages.map(stage => <div className="sleep-stage-row" key={stage}><span>{stageLabels[stage]}</span><div>{night.segments.filter(s => s.stage === stage).map(s => <i key={s.start} className={`sleep-${stage}`} style={{ left: `${(s.start - night.start) / span * 100}%`, width: `${Math.max(.15, (s.end - s.start) / span * 100)}%` }} title={`${stageLabels[stage]} · ${clockTime(s.start, zone)}–${clockTime(s.end, zone)} · ${minutesText((s.end - s.start) / 60000)}`}/>)}</div></div>)}</div><div className="sleep-time-axis"><span>{clockTime(night.start, zone)}</span><span>{clockTime(night.start + span / 2, zone)}</span><span>{clockTime(night.end, zone)}</span></div><div className="sleep-stage-totals">{stages.map(stage => <span key={stage}><i className={`sleep-${stage}`}/>{stageLabels[stage]} <strong>{minutesText(stage === "awake" ? night.awake : stage === "unknown" ? night.unknown : night.stages[stage])}</strong></span>)}</div><details className="sleep-records"><summary>View intervals as a table</summary><div className="sleep-table-scroll"><table><thead><tr><th>Stage</th><th>From</th><th>To</th><th>Duration</th></tr></thead><tbody>{night.segments.map(s => <tr key={s.start}><td>{stageLabels[s.stage]}</td><td>{clockTime(s.start, zone)}</td><td>{clockTime(s.end, zone)}</td><td>{minutesText((s.end - s.start) / 60000)}</td></tr>)}</tbody></table></div></details></>;
}
function Trend({ nights, from, count, selectedDay, select }: { nights: SleepNight[]; from: string; count: number; selectedDay: string; select: (date: string) => void }) {
  const byDay = new Map(nights.map(n => [n.date, n])), max = Math.max(600, ...nights.map(n => n.asleep + (n.awake || 0)));
  return <><div className="sleep-trend" aria-label="Daily sleep duration; select a bar to inspect that night">{Array.from({ length: count }, (_, i) => { const date = shiftDay(from, i), night = byDay.get(date); return <button key={date} aria-pressed={date === selectedDay} aria-label={`${dateLabel(date)}: ${night ? `${minutesText(night.asleep)} asleep; ${minutesText(night.awake)} recorded awake` : "no measured night"}`} title={`${dateLabel(date)} · ${night ? `${minutesText(night.asleep)} asleep / ${minutesText(night.awake)} awake` : "Missing"}`} onClick={() => select(date)}>{night ? <><span className="sleep-core" style={{ height: `${night.asleep / max * 100}%` }}/><span className="sleep-awake" style={{ height: `${(night.awake || 0) / max * 100}%` }}/></> : <span className="sleep-gap"/>}</button>; })}</div><div className="sleep-trend-axis"><span>{dateLabel(from)}</span><span>Scale: {minutesText(max)}</span><span>{dateLabel(shiftDay(from, count - 1))}</span></div></>;
}
function Timing({ nights, zone }: { nights: SleepNight[]; zone: string }) {
  const clockMinutes = (t: number) => { const parts = new Intl.DateTimeFormat("en-GB", { timeZone: zone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(t)); return Number(parts.find(p => p.type === "hour")?.value) * 60 + Number(parts.find(p => p.type === "minute")?.value); };
  const circular = (values: number[]) => { if (values.length < 3) return null; const x = average(values.map(v => Math.cos(v / 1440 * 2 * Math.PI)))!, y = average(values.map(v => Math.sin(v / 1440 * 2 * Math.PI)))!; const r = Math.min(1, Math.hypot(x, y)); return r < .01 ? null : Math.sqrt(-2 * Math.log(r)) * 1440 / (2 * Math.PI); };
  return <div className="sleep-timing"><Metric title="Sleep onset variability" value={minutesText(circular(nights.map(n => clockMinutes(n.start))))} detail={`${nights.length} nights · circular standard deviation`}/><Metric title="Wake-time variability" value={minutesText(circular(nights.map(n => clockMinutes(n.end))))} detail="At least 3 recorded nights needed"/></div>;
}
const contexts: { key: Exclude<keyof SleepContext, "date">; label: string; unit: string; digits: number }[] = [{ key: "steps", label: "Steps", unit: "", digits: 0 }, { key: "restingHeartRate", label: "Resting heart rate", unit: "bpm", digits: 1 }, { key: "hrv", label: "HRV", unit: "ms", digits: 1 }, { key: "activeEnergy", label: "Active energy", unit: "kcal", digits: 0 }, { key: "exerciseMinutes", label: "Exercise", unit: "min", digits: 0 }, { key: "respiratoryRate", label: "Respiratory rate", unit: "/min", digits: 1 }, { key: "oxygenSaturation", label: "Oxygen saturation", unit: "%", digits: 1 }];
function ContextGrid({ days, day }: { days: SleepContext[]; day: string }) { const current = days.find(d => d.date === day), previous = days.filter(d => d.date >= shiftDay(day, -28) && d.date < day); return <div className="sleep-context">{contexts.map(({ key, label, unit, digits }) => { const value = current?.[key], values = previous.flatMap(d => d[key] == null ? [] : [d[key]!]), baseline = values.length >= 7 ? median(values) : null, delta = value != null && baseline != null ? value - baseline : null; return <Metric key={key} title={label} value={value == null ? "—" : `${value.toLocaleString("en-US", { maximumFractionDigits: digits })} ${unit}`} detail={delta == null ? `${values.length}/28 baseline days; at least 7 needed` : `${delta >= 0 ? "+" : ""}${delta.toFixed(digits)} ${unit} vs. baseline median · ${values.length}/28 days`}/>; })}</div>; }
function AwakeHours({ nights, zone }: { nights: SleepNight[]; zone: string }) {
  const bins = useMemo(() => {
    const bins = Array.from({ length: 24 }, () => ({ awake: 0, coverage: 0, nights: 0 }));
    const hourFormat = new Intl.DateTimeFormat("en-GB", { timeZone: zone, hour: "2-digit", hourCycle: "h23" });
    for (const night of nights.filter(n => n.awake != null)) { const observed = new Set<number>(); for (const s of night.segments.filter(s => s.stage !== "unknown")) { for (let t = s.start; t < s.end;) { const next = Math.min(s.end, (Math.floor(t / 60000) + 1) * 60000), minutes = (next - t) / 60000; const hour = Number(hourFormat.format(new Date(t))); bins[hour].coverage += minutes; if (s.stage === "awake") bins[hour].awake += minutes; observed.add(hour); t = next; } } observed.forEach(hour => bins[hour].nights++); }
    return bins;
  }, [nights, zone]);
  const peak = Math.max(10, ...bins.map(b => b.nights ? b.awake / b.nights : 0));
  return <div className="sleep-hours">{Array.from({ length: 24 }, (_, i) => (i + 18) % 24).map(hour => { const b = bins[hour], value = b.nights ? b.awake / b.nights : null; return <div key={hour} title={`${hour}:00 · ${value == null ? "No coverage" : `${value.toFixed(1)} awake min per observed night; ${b.nights} nights; ${Math.round(b.coverage)} recorded minutes`}`}><span>{value == null ? "—" : value.toFixed(0)}</span><div><i style={{ height: value == null ? "0" : `${value / peak * 100}%` }}/></div><small>{hour.toString().padStart(2, "0")}</small></div>; })}</div>;
}
function SettingsEditor({ settings, revision, saving, save }: { settings: SleepSettings; revision: number; saving: boolean; save: (settings: SleepSettings, revision: number) => void }) { const [form, setForm] = useState(settings); const [baseRevision] = useState(revision); return <form className="editor-form" onSubmit={e => { e.preventDefault(); save(form, baseRevision); }}><label htmlFor="sleep-short">Short sleep: less than (minutes)</label><Input id="sleep-short" type="number" min={180} max={600} required value={form.shortMinutes} onChange={e => setForm({ ...form, shortMinutes: Number(e.target.value) })}/><label htmlFor="sleep-awake">Fragmentation: at least this much recorded awake (minutes)</label><Input id="sleep-awake" type="number" min={15} max={240} required value={form.awakeMinutes} onChange={e => setForm({ ...form, awakeMinutes: Number(e.target.value) })}/><label htmlFor="sleep-share">Or recorded sleep share below (%)</label><Input id="sleep-share" type="number" min={50} max={99} required value={form.sleepShare} onChange={e => setForm({ ...form, sleepShare: Number(e.target.value) })}/><p className="life-muted">Defaults (330 minutes asleep, 60 minutes awake, 85% share) come from the exploratory approach in your reference session. Missing data won’t trigger a flag.</p><Button type="submit" disabled={saving}>Save comparison settings</Button></form>; }
