"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowUpRight, BookOpen, Check, FileText, Plus, RefreshCw, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { emptyWriting, siteKinds, siteThreads, slugify, writingInputSchema, type WritingDraft, type WritingInput, type WritingView } from "@/lib/writing";

const label=(text:string)=>text.charAt(0).toUpperCase()+text.slice(1);
const inputOf=(draft:WritingDraft):WritingInput=>{const {updatedAt,exported,...input}=draft;void updatedAt;void exported;return input;};
function newDraft():WritingInput{return {id:crypto.randomUUID(),revision:0,title:"",slug:"",summary:"",body:"",timeframe:String(new Date().getFullYear()),kind:"writing",format:"Note",primaryThread:"writing",threads:["writing"],topics:[],relatedEntries:[]};}

export function WritingPanel(){
  const [view,setView]=useState<WritingView>(emptyWriting);const [loaded,setLoaded]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const locked=useRef(false);
  const [draft,setDraft]=useState<WritingInput|null>(null);const [saved,setSaved]=useState<WritingInput|null>(null);const [confirm,setConfirm]=useState(false);const [notice,setNotice]=useState("");const [discard,setDiscard]=useState(false);const [settings,setSettings]=useState(false);
  const dirty=!!draft&&JSON.stringify(draft)!==JSON.stringify(saved);
  const load=useCallback(async()=>{const response=await fetch("/api/writing",{cache:"no-store"});const value=await response.json() as WritingView & {error:string};if(!response.ok)throw new Error(value.error);setView(value);setLoaded(true);},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  async function perform(path:string,body:object){if(locked.current)return null;locked.current=true;setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/writing${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const value=await response.json() as WritingView & {error:string};if(!response.ok)throw new Error(value.error);setView(value);return value as WritingView;}catch(e){setError(e instanceof Error?e.message:"The draft could not be saved.");await load().catch(()=>{});return null;}finally{locked.current=false;setBusy(false);}}
  async function save(){if(!draft)return;const parsed=writingInputSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0]?.message||"Check your draft.");return;}const result=await perform("/save",parsed.data);const latest=result?.drafts.find(d=>d.id===draft.id);if(latest){const next=inputOf(latest);setDraft(next);setSaved(next);setNotice("Draft saved in Workspace.");}}
  const savedDraft=view.drafts.find(d=>d.id===draft?.id);const conflict=!!draft&&!!savedDraft&&draft.revision!==savedDraft.revision;const exported=conflict?null:savedDraft?.exported;const pending=!!draft&&view.pendingExports.includes(draft.id);
  const patch=(next:Partial<WritingInput>)=>draft&&setDraft({...draft,...next});
  const close=()=>{setDraft(null);setSaved(null);setError("");setNotice("");};
  return <div className="writing-panel">
    <div className="life-toolbar"><p>jordburg.com · {view.available?`${view.entries.length} entries in your site`:loaded?"Site connection needs attention":"Loading your writing…"}</p><div><Button variant="outline" onClick={()=>setSettings(true)}>Site connection</Button>{!draft&&<Button disabled={!loaded||busy} onClick={()=>{setDraft(newDraft());setSaved(null);setError("");setNotice("");}}><Plus size={16}/> New entry</Button>}</div></div>
    {view.error&&<p className="form-error" role="alert">{view.error}</p>}{error&&<p className="form-error" role="alert">{error} {!loaded&&<button className="text-button" onClick={()=>void load().catch(e=>setError(e.message))}>Retry</button>}</p>}{notice&&<p className="writing-notice" role="status"><Check size={16}/>{notice}</p>}
    {draft?<section className="writing-editor">
      <div className="writing-editor-toolbar"><button className="text-button" disabled={busy} onClick={()=>dirty?setDiscard(true):close()}><ArrowLeft size={16}/> All writing</button><span>{exported?"Handed off to site":dirty?"Unsaved changes":"Saved in Workspace"}</span></div>
      {conflict&&<div className="writing-handoff"><strong>A newer version is saved.</strong><p>Your text is still in this editor. Keep it as a separate draft to preserve both versions.</p><Button variant="outline" disabled={busy} onClick={()=>{if(!draft)return;const id=crypto.randomUUID();setDraft({...draft,id,revision:0,slug:`${draft.slug.slice(0,85).replace(/-$/,"")}-copy-${id.slice(0,6)}`});setSaved(null);setError("");setNotice("Your text is now a separate draft. Save it when you’re ready.");}}>Keep my text as a new draft</Button></div>}
      {pending&&<div className="writing-handoff"><strong>This handoff needs attention.</strong><p>Retry adding the saved draft, or recover it here. Recovery recognizes a completed handoff and leaves other site files untouched.</p><Button variant="outline" disabled={busy} onClick={async()=>{if(!draft)return;const result=await perform("/recover",{id:draft.id,revision:draft.revision});const latest=result?.drafts.find(d=>d.id===draft.id);if(latest){if(!dirty){setDraft(inputOf(latest));setSaved(inputOf(latest));}setNotice(dirty?"Handoff recovered. Your unsaved text is still here; keep it as a separate draft to preserve both versions.":latest.exported?"The completed handoff was recovered.":"Workspace draft recovered. You can edit its address and try again.");}}}>Recover saved draft</Button></div>}
      {exported&&<div className="writing-handoff"><strong>A saved copy of your handoff.</strong><p>This copy was added to the site as a draft. Its current content and publication status are managed in the site project.</p><code>{exported.file}</code></div>}
      <fieldset className="writing-fields" disabled={busy||!!exported||pending}>
        <label htmlFor="writing-title">Title</label><Input className="writing-title" id="writing-title" value={draft.title} placeholder="What have you been thinking about?" maxLength={200} onChange={e=>patch({title:e.target.value,...(!saved&&draft.slug===slugify(draft.title)?{slug:slugify(e.target.value)}:{})})}/>
        <div className="form-row"><div><label htmlFor="writing-kind">Kind</label><select id="writing-kind" value={draft.kind} onChange={e=>patch({kind:e.target.value as WritingInput["kind"]})}>{siteKinds.map(k=><option key={k} value={k}>{label(k)}</option>)}</select></div><div><label htmlFor="writing-format">Format</label><Input id="writing-format" value={draft.format} maxLength={100} placeholder="Note, essay, case study…" onChange={e=>patch({format:e.target.value})}/></div><div><label htmlFor="writing-timeframe">Timeframe</label><Input id="writing-timeframe" value={draft.timeframe} maxLength={100} placeholder="2026" onChange={e=>patch({timeframe:e.target.value})}/></div></div>
        <label htmlFor="writing-summary">Summary</label><textarea id="writing-summary" rows={2} maxLength={2000} value={draft.summary} placeholder="A short introduction for the site’s archive." onChange={e=>patch({summary:e.target.value})}/>
        <label htmlFor="writing-body">Entry <span className="optional">Markdown</span></label><textarea className="writing-body" id="writing-body" rows={16} maxLength={100000} value={draft.body} placeholder="Start writing here. Use ## for a heading, - for a list, and [label](url) for a link." onChange={e=>patch({body:e.target.value})}/>
        <details className="writing-details"><summary>Where it belongs on your site</summary><div className="form-row"><div><label htmlFor="writing-slug">Entry address</label><Input id="writing-slug" value={draft.slug} maxLength={100} onChange={e=>patch({slug:e.target.value})}/><p className="life-muted">/archive/{draft.slug||"entry-name"}/</p></div><div><label htmlFor="writing-thread">Primary thread</label><select id="writing-thread" value={draft.primaryThread} onChange={e=>{const t=e.target.value as WritingInput["primaryThread"];patch({primaryThread:t,threads:Array.from(new Set([...draft.threads,t]))});}}>{siteThreads.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></div></div>
        <fieldset className="writing-thread-options"><legend>Also include in</legend>{siteThreads.map(t=><label key={t}><input type="checkbox" checked={draft.threads.includes(t)} disabled={t===draft.primaryThread||busy||!!exported} onChange={e=>patch({threads:e.target.checked?[...draft.threads,t]:draft.threads.filter(v=>v!==t)})}/>{label(t)}</label>)}</fieldset>
        <label htmlFor="writing-topics">Topics <span className="optional">one per line</span></label><textarea id="writing-topics" rows={3} value={draft.topics.join("\n")} onChange={e=>patch({topics:e.target.value.split("\n")})} onBlur={()=>patch({topics:draft.topics.map(t=>t.trim()).filter(Boolean)})}/>
        <fieldset className="writing-related"><legend>Related entries <span className="optional">up to three</span></legend>{view.entries.filter(e=>e.slug!==draft.slug).map(entry=><label key={entry.slug}><input type="checkbox" checked={draft.relatedEntries.includes(entry.slug)} disabled={busy||!!exported||(!draft.relatedEntries.includes(entry.slug)&&draft.relatedEntries.length>=3)} onChange={e=>patch({relatedEntries:e.target.checked?[...draft.relatedEntries,entry.slug]:draft.relatedEntries.filter(s=>s!==entry.slug)})}/>{entry.title}</label>)}{draft.relatedEntries.filter(slug=>!view.entries.some(e=>e.slug===slug)).map(slug=><label key={slug}><input type="checkbox" checked disabled={busy||!!exported} onChange={()=>patch({relatedEntries:draft.relatedEntries.filter(s=>s!==slug)})}/>Not found in site: {slug} — uncheck to remove</label>)}</fieldset></details>
      </fieldset>
      {!exported&&<div className="writing-save-row"><p>{draft.body.trim()?`${draft.body.trim().split(/\s+/).length.toLocaleString()} words`:"A draft can start small."}</p><div><Button variant="outline" disabled={busy||pending||!draft.title.trim()} onClick={()=>void save()}>Save draft</Button><Button disabled={busy||dirty||!savedDraft||!view.available} onClick={()=>setConfirm(true)}><Send size={15}/> Add draft to site</Button></div></div>}
    </section>:<div className="writing-collection"><section><div className="life-section-heading"><h2>Your drafts</h2><span className="life-muted">{view.drafts.filter(d=>!d.exported).length} in progress</span></div>{!view.drafts.length?<div className="writing-empty"><FileText size={28}/><h3>A place to develop your next entry.</h3><p>Write and save here, then add a draft to your site when it’s ready for review.</p></div>:view.drafts.toSorted((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(d=><button className="writing-draft-row" key={d.id} onClick={()=>{const next=inputOf(d);setDraft(next);setSaved(next);setNotice("");setError("");}}><FileText size={20}/><span><strong>{d.title}</strong><small>{label(d.kind)} · {new Date(d.updatedAt).toLocaleDateString()} · {d.exported?"Sent to site":"Workspace draft"}</small></span><ArrowUpRight size={17}/></button>)}</section>
      <section className="writing-existing"><div className="life-section-heading"><h2>In your site</h2><a className="text-button" href="https://jordburg.com" target="_blank" rel="noreferrer">Visit site <ArrowUpRight size={15}/></a></div><p className="life-muted">The entries in your local site project.</p>{view.entries.map(entry=><article key={entry.slug}><BookOpen size={17}/><div><strong>{entry.title}</strong><p>{entry.summary}</p><small>{label(entry.kind)} · {label(entry.primaryThread)}{entry.draft?" · Draft":""}</small></div></article>)}</section>
    </div>}
    <Dialog open={confirm} onOpenChange={open=>!busy&&setConfirm(open)}><DialogContent className="editor-dialog"><DialogTitle>Add this draft to your site?</DialogTitle><DialogDescription>Creates a new Markdown entry in your personal site project. It stays a draft, visible in local development and excluded from the public site.</DialogDescription><p className="writing-confirm-title">{draft?.title}</p><p>After this handoff, continue editing in the site project. Workspace keeps the saved copy and never overwrites an existing site entry.</p><div className="editor-actions"><div><Button variant="ghost" disabled={busy} onClick={()=>setConfirm(false)}>Keep writing</Button><Button disabled={busy} onClick={async()=>{if(!draft)return;const result=await perform("/export",{id:draft.id,revision:draft.revision});const next=result?.drafts.find(d=>d.id===draft.id);if(next){setDraft(inputOf(next));setSaved(inputOf(next));setConfirm(false);setNotice("Added to the site as a draft. Review it in the site project before publishing.");}}}>{busy?"Adding…":"Add draft to site"}</Button></div></div>{error&&<p className="form-error" role="alert">{error}</p>}</DialogContent></Dialog>
    <Dialog open={discard} onOpenChange={setDiscard}><DialogContent className="editor-dialog"><DialogTitle>Leave this draft?</DialogTitle><DialogDescription>Your changes since the last save will be lost. The last saved version stays in Workspace.</DialogDescription><div className="editor-actions"><div><Button variant="outline" onClick={()=>setDiscard(false)}>Keep writing</Button><Button onClick={()=>{setDiscard(false);close();}}>Leave without saving</Button></div></div></DialogContent></Dialog>
    <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="editor-dialog"><DialogTitle>Personal site connection</DialogTitle><DialogDescription>Workspace reads your local personal-site project and can add new draft entries.</DialogDescription><p className="writing-path">{view.repository}</p><p>Drafts stay private in Workspace until you choose “Add draft to site.” Your site’s existing review and publishing process stays in place.</p><Button variant="outline" disabled={busy} onClick={()=>void load().then(()=>setError("")).catch(e=>setError(e.message))}><RefreshCw size={15}/> Refresh entries</Button></DialogContent></Dialog>
  </div>;
}
